// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package mocks

//go:generate minimock -i distributed-crawler/internal/application/service.CrawlTaskService -o crawl_task_service_minimock.go -n CrawlTaskServiceMock -p mocks

import (
	"context"
	mm_service "distributed-crawler/internal/application/service"
	"distributed-crawler/internal/domain/crawl/models"
	"distributed-crawler/internal/domain/crawl/valueobjects"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// CrawlTaskServiceMock implements mm_service.CrawlTaskService
type CrawlTaskServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateTask          func(ctx context.Context, cmd mm_service.CreateCrawlTaskCommand) (c2 valueobjects.CrawlTaskID, err error)
	funcCreateTaskOrigin    string
	inspectFuncCreateTask   func(ctx context.Context, cmd mm_service.CreateCrawlTaskCommand)
	afterCreateTaskCounter  uint64
	beforeCreateTaskCounter uint64
	CreateTaskMock          mCrawlTaskServiceMockCreateTask

	funcGetTask          func(ctx context.Context, query mm_service.GetCrawlTaskQuery) (cp1 *models.CrawlTask, err error)
	funcGetTaskOrigin    string
	inspectFuncGetTask   func(ctx context.Context, query mm_service.GetCrawlTaskQuery)
	afterGetTaskCounter  uint64
	beforeGetTaskCounter uint64
	GetTaskMock          mCrawlTaskServiceMockGetTask

	funcListTasksByJob          func(ctx context.Context, query mm_service.ListTasksByJobQuery) (cpa1 []*models.CrawlTask, err error)
	funcListTasksByJobOrigin    string
	inspectFuncListTasksByJob   func(ctx context.Context, query mm_service.ListTasksByJobQuery)
	afterListTasksByJobCounter  uint64
	beforeListTasksByJobCounter uint64
	ListTasksByJobMock          mCrawlTaskServiceMockListTasksByJob

	funcUpdateTaskStatus          func(ctx context.Context, cmd mm_service.UpdateTaskStatusCommand) (err error)
	funcUpdateTaskStatusOrigin    string
	inspectFuncUpdateTaskStatus   func(ctx context.Context, cmd mm_service.UpdateTaskStatusCommand)
	afterUpdateTaskStatusCounter  uint64
	beforeUpdateTaskStatusCounter uint64
	UpdateTaskStatusMock          mCrawlTaskServiceMockUpdateTaskStatus
}

// NewCrawlTaskServiceMock returns a mock for mm_service.CrawlTaskService
func NewCrawlTaskServiceMock(t minimock.Tester) *CrawlTaskServiceMock {
	m := &CrawlTaskServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateTaskMock = mCrawlTaskServiceMockCreateTask{mock: m}
	m.CreateTaskMock.callArgs = []*CrawlTaskServiceMockCreateTaskParams{}

	m.GetTaskMock = mCrawlTaskServiceMockGetTask{mock: m}
	m.GetTaskMock.callArgs = []*CrawlTaskServiceMockGetTaskParams{}

	m.ListTasksByJobMock = mCrawlTaskServiceMockListTasksByJob{mock: m}
	m.ListTasksByJobMock.callArgs = []*CrawlTaskServiceMockListTasksByJobParams{}

	m.UpdateTaskStatusMock = mCrawlTaskServiceMockUpdateTaskStatus{mock: m}
	m.UpdateTaskStatusMock.callArgs = []*CrawlTaskServiceMockUpdateTaskStatusParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCrawlTaskServiceMockCreateTask struct {
	optional           bool
	mock               *CrawlTaskServiceMock
	defaultExpectation *CrawlTaskServiceMockCreateTaskExpectation
	expectations       []*CrawlTaskServiceMockCreateTaskExpectation

	callArgs []*CrawlTaskServiceMockCreateTaskParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CrawlTaskServiceMockCreateTaskExpectation specifies expectation struct of the CrawlTaskService.CreateTask
type CrawlTaskServiceMockCreateTaskExpectation struct {
	mock               *CrawlTaskServiceMock
	params             *CrawlTaskServiceMockCreateTaskParams
	paramPtrs          *CrawlTaskServiceMockCreateTaskParamPtrs
	expectationOrigins CrawlTaskServiceMockCreateTaskExpectationOrigins
	results            *CrawlTaskServiceMockCreateTaskResults
	returnOrigin       string
	Counter            uint64
}

// CrawlTaskServiceMockCreateTaskParams contains parameters of the CrawlTaskService.CreateTask
type CrawlTaskServiceMockCreateTaskParams struct {
	ctx context.Context
	cmd mm_service.CreateCrawlTaskCommand
}

// CrawlTaskServiceMockCreateTaskParamPtrs contains pointers to parameters of the CrawlTaskService.CreateTask
type CrawlTaskServiceMockCreateTaskParamPtrs struct {
	ctx *context.Context
	cmd *mm_service.CreateCrawlTaskCommand
}

// CrawlTaskServiceMockCreateTaskResults contains results of the CrawlTaskService.CreateTask
type CrawlTaskServiceMockCreateTaskResults struct {
	c2  valueobjects.CrawlTaskID
	err error
}

// CrawlTaskServiceMockCreateTaskOrigins contains origins of expectations of the CrawlTaskService.CreateTask
type CrawlTaskServiceMockCreateTaskExpectationOrigins struct {
	origin    string
	originCtx string
	originCmd string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) Optional() *mCrawlTaskServiceMockCreateTask {
	mmCreateTask.optional = true
	return mmCreateTask
}

// Expect sets up expected params for CrawlTaskService.CreateTask
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) Expect(ctx context.Context, cmd mm_service.CreateCrawlTaskCommand) *mCrawlTaskServiceMockCreateTask {
	if mmCreateTask.mock.funcCreateTask != nil {
		mmCreateTask.mock.t.Fatalf("CrawlTaskServiceMock.CreateTask mock is already set by Set")
	}

	if mmCreateTask.defaultExpectation == nil {
		mmCreateTask.defaultExpectation = &CrawlTaskServiceMockCreateTaskExpectation{}
	}

	if mmCreateTask.defaultExpectation.paramPtrs != nil {
		mmCreateTask.mock.t.Fatalf("CrawlTaskServiceMock.CreateTask mock is already set by ExpectParams functions")
	}

	mmCreateTask.defaultExpectation.params = &CrawlTaskServiceMockCreateTaskParams{ctx, cmd}
	mmCreateTask.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateTask.expectations {
		if minimock.Equal(e.params, mmCreateTask.defaultExpectation.params) {
			mmCreateTask.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateTask.defaultExpectation.params)
		}
	}

	return mmCreateTask
}

// ExpectCtxParam1 sets up expected param ctx for CrawlTaskService.CreateTask
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) ExpectCtxParam1(ctx context.Context) *mCrawlTaskServiceMockCreateTask {
	if mmCreateTask.mock.funcCreateTask != nil {
		mmCreateTask.mock.t.Fatalf("CrawlTaskServiceMock.CreateTask mock is already set by Set")
	}

	if mmCreateTask.defaultExpectation == nil {
		mmCreateTask.defaultExpectation = &CrawlTaskServiceMockCreateTaskExpectation{}
	}

	if mmCreateTask.defaultExpectation.params != nil {
		mmCreateTask.mock.t.Fatalf("CrawlTaskServiceMock.CreateTask mock is already set by Expect")
	}

	if mmCreateTask.defaultExpectation.paramPtrs == nil {
		mmCreateTask.defaultExpectation.paramPtrs = &CrawlTaskServiceMockCreateTaskParamPtrs{}
	}
	mmCreateTask.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateTask.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateTask
}

// ExpectCmdParam2 sets up expected param cmd for CrawlTaskService.CreateTask
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) ExpectCmdParam2(cmd mm_service.CreateCrawlTaskCommand) *mCrawlTaskServiceMockCreateTask {
	if mmCreateTask.mock.funcCreateTask != nil {
		mmCreateTask.mock.t.Fatalf("CrawlTaskServiceMock.CreateTask mock is already set by Set")
	}

	if mmCreateTask.defaultExpectation == nil {
		mmCreateTask.defaultExpectation = &CrawlTaskServiceMockCreateTaskExpectation{}
	}

	if mmCreateTask.defaultExpectation.params != nil {
		mmCreateTask.mock.t.Fatalf("CrawlTaskServiceMock.CreateTask mock is already set by Expect")
	}

	if mmCreateTask.defaultExpectation.paramPtrs == nil {
		mmCreateTask.defaultExpectation.paramPtrs = &CrawlTaskServiceMockCreateTaskParamPtrs{}
	}
	mmCreateTask.defaultExpectation.paramPtrs.cmd = &cmd
	mmCreateTask.defaultExpectation.expectationOrigins.originCmd = minimock.CallerInfo(1)

	return mmCreateTask
}

// Inspect accepts an inspector function that has same arguments as the CrawlTaskService.CreateTask
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) Inspect(f func(ctx context.Context, cmd mm_service.CreateCrawlTaskCommand)) *mCrawlTaskServiceMockCreateTask {
	if mmCreateTask.mock.inspectFuncCreateTask != nil {
		mmCreateTask.mock.t.Fatalf("Inspect function is already set for CrawlTaskServiceMock.CreateTask")
	}

	mmCreateTask.mock.inspectFuncCreateTask = f

	return mmCreateTask
}

// Return sets up results that will be returned by CrawlTaskService.CreateTask
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) Return(c2 valueobjects.CrawlTaskID, err error) *CrawlTaskServiceMock {
	if mmCreateTask.mock.funcCreateTask != nil {
		mmCreateTask.mock.t.Fatalf("CrawlTaskServiceMock.CreateTask mock is already set by Set")
	}

	if mmCreateTask.defaultExpectation == nil {
		mmCreateTask.defaultExpectation = &CrawlTaskServiceMockCreateTaskExpectation{mock: mmCreateTask.mock}
	}
	mmCreateTask.defaultExpectation.results = &CrawlTaskServiceMockCreateTaskResults{c2, err}
	mmCreateTask.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateTask.mock
}

// Set uses given function f to mock the CrawlTaskService.CreateTask method
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) Set(f func(ctx context.Context, cmd mm_service.CreateCrawlTaskCommand) (c2 valueobjects.CrawlTaskID, err error)) *CrawlTaskServiceMock {
	if mmCreateTask.defaultExpectation != nil {
		mmCreateTask.mock.t.Fatalf("Default expectation is already set for the CrawlTaskService.CreateTask method")
	}

	if len(mmCreateTask.expectations) > 0 {
		mmCreateTask.mock.t.Fatalf("Some expectations are already set for the CrawlTaskService.CreateTask method")
	}

	mmCreateTask.mock.funcCreateTask = f
	mmCreateTask.mock.funcCreateTaskOrigin = minimock.CallerInfo(1)
	return mmCreateTask.mock
}

// When sets expectation for the CrawlTaskService.CreateTask which will trigger the result defined by the following
// Then helper
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) When(ctx context.Context, cmd mm_service.CreateCrawlTaskCommand) *CrawlTaskServiceMockCreateTaskExpectation {
	if mmCreateTask.mock.funcCreateTask != nil {
		mmCreateTask.mock.t.Fatalf("CrawlTaskServiceMock.CreateTask mock is already set by Set")
	}

	expectation := &CrawlTaskServiceMockCreateTaskExpectation{
		mock:               mmCreateTask.mock,
		params:             &CrawlTaskServiceMockCreateTaskParams{ctx, cmd},
		expectationOrigins: CrawlTaskServiceMockCreateTaskExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateTask.expectations = append(mmCreateTask.expectations, expectation)
	return expectation
}

// Then sets up CrawlTaskService.CreateTask return parameters for the expectation previously defined by the When method
func (e *CrawlTaskServiceMockCreateTaskExpectation) Then(c2 valueobjects.CrawlTaskID, err error) *CrawlTaskServiceMock {
	e.results = &CrawlTaskServiceMockCreateTaskResults{c2, err}
	return e.mock
}

// Times sets number of times CrawlTaskService.CreateTask should be invoked
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) Times(n uint64) *mCrawlTaskServiceMockCreateTask {
	if n == 0 {
		mmCreateTask.mock.t.Fatalf("Times of CrawlTaskServiceMock.CreateTask mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateTask.expectedInvocations, n)
	mmCreateTask.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateTask
}

func (mmCreateTask *mCrawlTaskServiceMockCreateTask) invocationsDone() bool {
	if len(mmCreateTask.expectations) == 0 && mmCreateTask.defaultExpectation == nil && mmCreateTask.mock.funcCreateTask == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateTask.mock.afterCreateTaskCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateTask.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateTask implements mm_service.CrawlTaskService
func (mmCreateTask *CrawlTaskServiceMock) CreateTask(ctx context.Context, cmd mm_service.CreateCrawlTaskCommand) (c2 valueobjects.CrawlTaskID, err error) {
	mm_atomic.AddUint64(&mmCreateTask.beforeCreateTaskCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateTask.afterCreateTaskCounter, 1)

	mmCreateTask.t.Helper()

	if mmCreateTask.inspectFuncCreateTask != nil {
		mmCreateTask.inspectFuncCreateTask(ctx, cmd)
	}

	mm_params := CrawlTaskServiceMockCreateTaskParams{ctx, cmd}

	// Record call args
	mmCreateTask.CreateTaskMock.mutex.Lock()
	mmCreateTask.CreateTaskMock.callArgs = append(mmCreateTask.CreateTaskMock.callArgs, &mm_params)
	mmCreateTask.CreateTaskMock.mutex.Unlock()

	for _, e := range mmCreateTask.CreateTaskMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c2, e.results.err
		}
	}

	if mmCreateTask.CreateTaskMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateTask.CreateTaskMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateTask.CreateTaskMock.defaultExpectation.params
		mm_want_ptrs := mmCreateTask.CreateTaskMock.defaultExpectation.paramPtrs

		mm_got := CrawlTaskServiceMockCreateTaskParams{ctx, cmd}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateTask.t.Errorf("CrawlTaskServiceMock.CreateTask got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateTask.CreateTaskMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.cmd != nil && !minimock.Equal(*mm_want_ptrs.cmd, mm_got.cmd) {
				mmCreateTask.t.Errorf("CrawlTaskServiceMock.CreateTask got unexpected parameter cmd, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateTask.CreateTaskMock.defaultExpectation.expectationOrigins.originCmd, *mm_want_ptrs.cmd, mm_got.cmd, minimock.Diff(*mm_want_ptrs.cmd, mm_got.cmd))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateTask.t.Errorf("CrawlTaskServiceMock.CreateTask got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateTask.CreateTaskMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateTask.CreateTaskMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateTask.t.Fatal("No results are set for the CrawlTaskServiceMock.CreateTask")
		}
		return (*mm_results).c2, (*mm_results).err
	}
	if mmCreateTask.funcCreateTask != nil {
		return mmCreateTask.funcCreateTask(ctx, cmd)
	}
	mmCreateTask.t.Fatalf("Unexpected call to CrawlTaskServiceMock.CreateTask. %v %v", ctx, cmd)
	return
}

// CreateTaskAfterCounter returns a count of finished CrawlTaskServiceMock.CreateTask invocations
func (mmCreateTask *CrawlTaskServiceMock) CreateTaskAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateTask.afterCreateTaskCounter)
}

// CreateTaskBeforeCounter returns a count of CrawlTaskServiceMock.CreateTask invocations
func (mmCreateTask *CrawlTaskServiceMock) CreateTaskBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateTask.beforeCreateTaskCounter)
}

// Calls returns a list of arguments used in each call to CrawlTaskServiceMock.CreateTask.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateTask *mCrawlTaskServiceMockCreateTask) Calls() []*CrawlTaskServiceMockCreateTaskParams {
	mmCreateTask.mutex.RLock()

	argCopy := make([]*CrawlTaskServiceMockCreateTaskParams, len(mmCreateTask.callArgs))
	copy(argCopy, mmCreateTask.callArgs)

	mmCreateTask.mutex.RUnlock()

	return argCopy
}

// MinimockCreateTaskDone returns true if the count of the CreateTask invocations corresponds
// the number of defined expectations
func (m *CrawlTaskServiceMock) MinimockCreateTaskDone() bool {
	if m.CreateTaskMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateTaskMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateTaskMock.invocationsDone()
}

// MinimockCreateTaskInspect logs each unmet expectation
func (m *CrawlTaskServiceMock) MinimockCreateTaskInspect() {
	for _, e := range m.CreateTaskMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.CreateTask at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateTaskCounter := mm_atomic.LoadUint64(&m.afterCreateTaskCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateTaskMock.defaultExpectation != nil && afterCreateTaskCounter < 1 {
		if m.CreateTaskMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.CreateTask at\n%s", m.CreateTaskMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.CreateTask at\n%s with params: %#v", m.CreateTaskMock.defaultExpectation.expectationOrigins.origin, *m.CreateTaskMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateTask != nil && afterCreateTaskCounter < 1 {
		m.t.Errorf("Expected call to CrawlTaskServiceMock.CreateTask at\n%s", m.funcCreateTaskOrigin)
	}

	if !m.CreateTaskMock.invocationsDone() && afterCreateTaskCounter > 0 {
		m.t.Errorf("Expected %d calls to CrawlTaskServiceMock.CreateTask at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateTaskMock.expectedInvocations), m.CreateTaskMock.expectedInvocationsOrigin, afterCreateTaskCounter)
	}
}

type mCrawlTaskServiceMockGetTask struct {
	optional           bool
	mock               *CrawlTaskServiceMock
	defaultExpectation *CrawlTaskServiceMockGetTaskExpectation
	expectations       []*CrawlTaskServiceMockGetTaskExpectation

	callArgs []*CrawlTaskServiceMockGetTaskParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CrawlTaskServiceMockGetTaskExpectation specifies expectation struct of the CrawlTaskService.GetTask
type CrawlTaskServiceMockGetTaskExpectation struct {
	mock               *CrawlTaskServiceMock
	params             *CrawlTaskServiceMockGetTaskParams
	paramPtrs          *CrawlTaskServiceMockGetTaskParamPtrs
	expectationOrigins CrawlTaskServiceMockGetTaskExpectationOrigins
	results            *CrawlTaskServiceMockGetTaskResults
	returnOrigin       string
	Counter            uint64
}

// CrawlTaskServiceMockGetTaskParams contains parameters of the CrawlTaskService.GetTask
type CrawlTaskServiceMockGetTaskParams struct {
	ctx   context.Context
	query mm_service.GetCrawlTaskQuery
}

// CrawlTaskServiceMockGetTaskParamPtrs contains pointers to parameters of the CrawlTaskService.GetTask
type CrawlTaskServiceMockGetTaskParamPtrs struct {
	ctx   *context.Context
	query *mm_service.GetCrawlTaskQuery
}

// CrawlTaskServiceMockGetTaskResults contains results of the CrawlTaskService.GetTask
type CrawlTaskServiceMockGetTaskResults struct {
	cp1 *models.CrawlTask
	err error
}

// CrawlTaskServiceMockGetTaskOrigins contains origins of expectations of the CrawlTaskService.GetTask
type CrawlTaskServiceMockGetTaskExpectationOrigins struct {
	origin      string
	originCtx   string
	originQuery string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetTask *mCrawlTaskServiceMockGetTask) Optional() *mCrawlTaskServiceMockGetTask {
	mmGetTask.optional = true
	return mmGetTask
}

// Expect sets up expected params for CrawlTaskService.GetTask
func (mmGetTask *mCrawlTaskServiceMockGetTask) Expect(ctx context.Context, query mm_service.GetCrawlTaskQuery) *mCrawlTaskServiceMockGetTask {
	if mmGetTask.mock.funcGetTask != nil {
		mmGetTask.mock.t.Fatalf("CrawlTaskServiceMock.GetTask mock is already set by Set")
	}

	if mmGetTask.defaultExpectation == nil {
		mmGetTask.defaultExpectation = &CrawlTaskServiceMockGetTaskExpectation{}
	}

	if mmGetTask.defaultExpectation.paramPtrs != nil {
		mmGetTask.mock.t.Fatalf("CrawlTaskServiceMock.GetTask mock is already set by ExpectParams functions")
	}

	mmGetTask.defaultExpectation.params = &CrawlTaskServiceMockGetTaskParams{ctx, query}
	mmGetTask.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetTask.expectations {
		if minimock.Equal(e.params, mmGetTask.defaultExpectation.params) {
			mmGetTask.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetTask.defaultExpectation.params)
		}
	}

	return mmGetTask
}

// ExpectCtxParam1 sets up expected param ctx for CrawlTaskService.GetTask
func (mmGetTask *mCrawlTaskServiceMockGetTask) ExpectCtxParam1(ctx context.Context) *mCrawlTaskServiceMockGetTask {
	if mmGetTask.mock.funcGetTask != nil {
		mmGetTask.mock.t.Fatalf("CrawlTaskServiceMock.GetTask mock is already set by Set")
	}

	if mmGetTask.defaultExpectation == nil {
		mmGetTask.defaultExpectation = &CrawlTaskServiceMockGetTaskExpectation{}
	}

	if mmGetTask.defaultExpectation.params != nil {
		mmGetTask.mock.t.Fatalf("CrawlTaskServiceMock.GetTask mock is already set by Expect")
	}

	if mmGetTask.defaultExpectation.paramPtrs == nil {
		mmGetTask.defaultExpectation.paramPtrs = &CrawlTaskServiceMockGetTaskParamPtrs{}
	}
	mmGetTask.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetTask.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetTask
}

// ExpectQueryParam2 sets up expected param query for CrawlTaskService.GetTask
func (mmGetTask *mCrawlTaskServiceMockGetTask) ExpectQueryParam2(query mm_service.GetCrawlTaskQuery) *mCrawlTaskServiceMockGetTask {
	if mmGetTask.mock.funcGetTask != nil {
		mmGetTask.mock.t.Fatalf("CrawlTaskServiceMock.GetTask mock is already set by Set")
	}

	if mmGetTask.defaultExpectation == nil {
		mmGetTask.defaultExpectation = &CrawlTaskServiceMockGetTaskExpectation{}
	}

	if mmGetTask.defaultExpectation.params != nil {
		mmGetTask.mock.t.Fatalf("CrawlTaskServiceMock.GetTask mock is already set by Expect")
	}

	if mmGetTask.defaultExpectation.paramPtrs == nil {
		mmGetTask.defaultExpectation.paramPtrs = &CrawlTaskServiceMockGetTaskParamPtrs{}
	}
	mmGetTask.defaultExpectation.paramPtrs.query = &query
	mmGetTask.defaultExpectation.expectationOrigins.originQuery = minimock.CallerInfo(1)

	return mmGetTask
}

// Inspect accepts an inspector function that has same arguments as the CrawlTaskService.GetTask
func (mmGetTask *mCrawlTaskServiceMockGetTask) Inspect(f func(ctx context.Context, query mm_service.GetCrawlTaskQuery)) *mCrawlTaskServiceMockGetTask {
	if mmGetTask.mock.inspectFuncGetTask != nil {
		mmGetTask.mock.t.Fatalf("Inspect function is already set for CrawlTaskServiceMock.GetTask")
	}

	mmGetTask.mock.inspectFuncGetTask = f

	return mmGetTask
}

// Return sets up results that will be returned by CrawlTaskService.GetTask
func (mmGetTask *mCrawlTaskServiceMockGetTask) Return(cp1 *models.CrawlTask, err error) *CrawlTaskServiceMock {
	if mmGetTask.mock.funcGetTask != nil {
		mmGetTask.mock.t.Fatalf("CrawlTaskServiceMock.GetTask mock is already set by Set")
	}

	if mmGetTask.defaultExpectation == nil {
		mmGetTask.defaultExpectation = &CrawlTaskServiceMockGetTaskExpectation{mock: mmGetTask.mock}
	}
	mmGetTask.defaultExpectation.results = &CrawlTaskServiceMockGetTaskResults{cp1, err}
	mmGetTask.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetTask.mock
}

// Set uses given function f to mock the CrawlTaskService.GetTask method
func (mmGetTask *mCrawlTaskServiceMockGetTask) Set(f func(ctx context.Context, query mm_service.GetCrawlTaskQuery) (cp1 *models.CrawlTask, err error)) *CrawlTaskServiceMock {
	if mmGetTask.defaultExpectation != nil {
		mmGetTask.mock.t.Fatalf("Default expectation is already set for the CrawlTaskService.GetTask method")
	}

	if len(mmGetTask.expectations) > 0 {
		mmGetTask.mock.t.Fatalf("Some expectations are already set for the CrawlTaskService.GetTask method")
	}

	mmGetTask.mock.funcGetTask = f
	mmGetTask.mock.funcGetTaskOrigin = minimock.CallerInfo(1)
	return mmGetTask.mock
}

// When sets expectation for the CrawlTaskService.GetTask which will trigger the result defined by the following
// Then helper
func (mmGetTask *mCrawlTaskServiceMockGetTask) When(ctx context.Context, query mm_service.GetCrawlTaskQuery) *CrawlTaskServiceMockGetTaskExpectation {
	if mmGetTask.mock.funcGetTask != nil {
		mmGetTask.mock.t.Fatalf("CrawlTaskServiceMock.GetTask mock is already set by Set")
	}

	expectation := &CrawlTaskServiceMockGetTaskExpectation{
		mock:               mmGetTask.mock,
		params:             &CrawlTaskServiceMockGetTaskParams{ctx, query},
		expectationOrigins: CrawlTaskServiceMockGetTaskExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetTask.expectations = append(mmGetTask.expectations, expectation)
	return expectation
}

// Then sets up CrawlTaskService.GetTask return parameters for the expectation previously defined by the When method
func (e *CrawlTaskServiceMockGetTaskExpectation) Then(cp1 *models.CrawlTask, err error) *CrawlTaskServiceMock {
	e.results = &CrawlTaskServiceMockGetTaskResults{cp1, err}
	return e.mock
}

// Times sets number of times CrawlTaskService.GetTask should be invoked
func (mmGetTask *mCrawlTaskServiceMockGetTask) Times(n uint64) *mCrawlTaskServiceMockGetTask {
	if n == 0 {
		mmGetTask.mock.t.Fatalf("Times of CrawlTaskServiceMock.GetTask mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetTask.expectedInvocations, n)
	mmGetTask.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetTask
}

func (mmGetTask *mCrawlTaskServiceMockGetTask) invocationsDone() bool {
	if len(mmGetTask.expectations) == 0 && mmGetTask.defaultExpectation == nil && mmGetTask.mock.funcGetTask == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetTask.mock.afterGetTaskCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetTask.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetTask implements mm_service.CrawlTaskService
func (mmGetTask *CrawlTaskServiceMock) GetTask(ctx context.Context, query mm_service.GetCrawlTaskQuery) (cp1 *models.CrawlTask, err error) {
	mm_atomic.AddUint64(&mmGetTask.beforeGetTaskCounter, 1)
	defer mm_atomic.AddUint64(&mmGetTask.afterGetTaskCounter, 1)

	mmGetTask.t.Helper()

	if mmGetTask.inspectFuncGetTask != nil {
		mmGetTask.inspectFuncGetTask(ctx, query)
	}

	mm_params := CrawlTaskServiceMockGetTaskParams{ctx, query}

	// Record call args
	mmGetTask.GetTaskMock.mutex.Lock()
	mmGetTask.GetTaskMock.callArgs = append(mmGetTask.GetTaskMock.callArgs, &mm_params)
	mmGetTask.GetTaskMock.mutex.Unlock()

	for _, e := range mmGetTask.GetTaskMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmGetTask.GetTaskMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetTask.GetTaskMock.defaultExpectation.Counter, 1)
		mm_want := mmGetTask.GetTaskMock.defaultExpectation.params
		mm_want_ptrs := mmGetTask.GetTaskMock.defaultExpectation.paramPtrs

		mm_got := CrawlTaskServiceMockGetTaskParams{ctx, query}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetTask.t.Errorf("CrawlTaskServiceMock.GetTask got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetTask.GetTaskMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.query != nil && !minimock.Equal(*mm_want_ptrs.query, mm_got.query) {
				mmGetTask.t.Errorf("CrawlTaskServiceMock.GetTask got unexpected parameter query, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetTask.GetTaskMock.defaultExpectation.expectationOrigins.originQuery, *mm_want_ptrs.query, mm_got.query, minimock.Diff(*mm_want_ptrs.query, mm_got.query))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetTask.t.Errorf("CrawlTaskServiceMock.GetTask got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetTask.GetTaskMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetTask.GetTaskMock.defaultExpectation.results
		if mm_results == nil {
			mmGetTask.t.Fatal("No results are set for the CrawlTaskServiceMock.GetTask")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmGetTask.funcGetTask != nil {
		return mmGetTask.funcGetTask(ctx, query)
	}
	mmGetTask.t.Fatalf("Unexpected call to CrawlTaskServiceMock.GetTask. %v %v", ctx, query)
	return
}

// GetTaskAfterCounter returns a count of finished CrawlTaskServiceMock.GetTask invocations
func (mmGetTask *CrawlTaskServiceMock) GetTaskAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetTask.afterGetTaskCounter)
}

// GetTaskBeforeCounter returns a count of CrawlTaskServiceMock.GetTask invocations
func (mmGetTask *CrawlTaskServiceMock) GetTaskBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetTask.beforeGetTaskCounter)
}

// Calls returns a list of arguments used in each call to CrawlTaskServiceMock.GetTask.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetTask *mCrawlTaskServiceMockGetTask) Calls() []*CrawlTaskServiceMockGetTaskParams {
	mmGetTask.mutex.RLock()

	argCopy := make([]*CrawlTaskServiceMockGetTaskParams, len(mmGetTask.callArgs))
	copy(argCopy, mmGetTask.callArgs)

	mmGetTask.mutex.RUnlock()

	return argCopy
}

// MinimockGetTaskDone returns true if the count of the GetTask invocations corresponds
// the number of defined expectations
func (m *CrawlTaskServiceMock) MinimockGetTaskDone() bool {
	if m.GetTaskMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetTaskMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetTaskMock.invocationsDone()
}

// MinimockGetTaskInspect logs each unmet expectation
func (m *CrawlTaskServiceMock) MinimockGetTaskInspect() {
	for _, e := range m.GetTaskMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.GetTask at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetTaskCounter := mm_atomic.LoadUint64(&m.afterGetTaskCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetTaskMock.defaultExpectation != nil && afterGetTaskCounter < 1 {
		if m.GetTaskMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.GetTask at\n%s", m.GetTaskMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.GetTask at\n%s with params: %#v", m.GetTaskMock.defaultExpectation.expectationOrigins.origin, *m.GetTaskMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetTask != nil && afterGetTaskCounter < 1 {
		m.t.Errorf("Expected call to CrawlTaskServiceMock.GetTask at\n%s", m.funcGetTaskOrigin)
	}

	if !m.GetTaskMock.invocationsDone() && afterGetTaskCounter > 0 {
		m.t.Errorf("Expected %d calls to CrawlTaskServiceMock.GetTask at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetTaskMock.expectedInvocations), m.GetTaskMock.expectedInvocationsOrigin, afterGetTaskCounter)
	}
}

type mCrawlTaskServiceMockListTasksByJob struct {
	optional           bool
	mock               *CrawlTaskServiceMock
	defaultExpectation *CrawlTaskServiceMockListTasksByJobExpectation
	expectations       []*CrawlTaskServiceMockListTasksByJobExpectation

	callArgs []*CrawlTaskServiceMockListTasksByJobParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CrawlTaskServiceMockListTasksByJobExpectation specifies expectation struct of the CrawlTaskService.ListTasksByJob
type CrawlTaskServiceMockListTasksByJobExpectation struct {
	mock               *CrawlTaskServiceMock
	params             *CrawlTaskServiceMockListTasksByJobParams
	paramPtrs          *CrawlTaskServiceMockListTasksByJobParamPtrs
	expectationOrigins CrawlTaskServiceMockListTasksByJobExpectationOrigins
	results            *CrawlTaskServiceMockListTasksByJobResults
	returnOrigin       string
	Counter            uint64
}

// CrawlTaskServiceMockListTasksByJobParams contains parameters of the CrawlTaskService.ListTasksByJob
type CrawlTaskServiceMockListTasksByJobParams struct {
	ctx   context.Context
	query mm_service.ListTasksByJobQuery
}

// CrawlTaskServiceMockListTasksByJobParamPtrs contains pointers to parameters of the CrawlTaskService.ListTasksByJob
type CrawlTaskServiceMockListTasksByJobParamPtrs struct {
	ctx   *context.Context
	query *mm_service.ListTasksByJobQuery
}

// CrawlTaskServiceMockListTasksByJobResults contains results of the CrawlTaskService.ListTasksByJob
type CrawlTaskServiceMockListTasksByJobResults struct {
	cpa1 []*models.CrawlTask
	err  error
}

// CrawlTaskServiceMockListTasksByJobOrigins contains origins of expectations of the CrawlTaskService.ListTasksByJob
type CrawlTaskServiceMockListTasksByJobExpectationOrigins struct {
	origin      string
	originCtx   string
	originQuery string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) Optional() *mCrawlTaskServiceMockListTasksByJob {
	mmListTasksByJob.optional = true
	return mmListTasksByJob
}

// Expect sets up expected params for CrawlTaskService.ListTasksByJob
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) Expect(ctx context.Context, query mm_service.ListTasksByJobQuery) *mCrawlTaskServiceMockListTasksByJob {
	if mmListTasksByJob.mock.funcListTasksByJob != nil {
		mmListTasksByJob.mock.t.Fatalf("CrawlTaskServiceMock.ListTasksByJob mock is already set by Set")
	}

	if mmListTasksByJob.defaultExpectation == nil {
		mmListTasksByJob.defaultExpectation = &CrawlTaskServiceMockListTasksByJobExpectation{}
	}

	if mmListTasksByJob.defaultExpectation.paramPtrs != nil {
		mmListTasksByJob.mock.t.Fatalf("CrawlTaskServiceMock.ListTasksByJob mock is already set by ExpectParams functions")
	}

	mmListTasksByJob.defaultExpectation.params = &CrawlTaskServiceMockListTasksByJobParams{ctx, query}
	mmListTasksByJob.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListTasksByJob.expectations {
		if minimock.Equal(e.params, mmListTasksByJob.defaultExpectation.params) {
			mmListTasksByJob.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListTasksByJob.defaultExpectation.params)
		}
	}

	return mmListTasksByJob
}

// ExpectCtxParam1 sets up expected param ctx for CrawlTaskService.ListTasksByJob
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) ExpectCtxParam1(ctx context.Context) *mCrawlTaskServiceMockListTasksByJob {
	if mmListTasksByJob.mock.funcListTasksByJob != nil {
		mmListTasksByJob.mock.t.Fatalf("CrawlTaskServiceMock.ListTasksByJob mock is already set by Set")
	}

	if mmListTasksByJob.defaultExpectation == nil {
		mmListTasksByJob.defaultExpectation = &CrawlTaskServiceMockListTasksByJobExpectation{}
	}

	if mmListTasksByJob.defaultExpectation.params != nil {
		mmListTasksByJob.mock.t.Fatalf("CrawlTaskServiceMock.ListTasksByJob mock is already set by Expect")
	}

	if mmListTasksByJob.defaultExpectation.paramPtrs == nil {
		mmListTasksByJob.defaultExpectation.paramPtrs = &CrawlTaskServiceMockListTasksByJobParamPtrs{}
	}
	mmListTasksByJob.defaultExpectation.paramPtrs.ctx = &ctx
	mmListTasksByJob.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListTasksByJob
}

// ExpectQueryParam2 sets up expected param query for CrawlTaskService.ListTasksByJob
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) ExpectQueryParam2(query mm_service.ListTasksByJobQuery) *mCrawlTaskServiceMockListTasksByJob {
	if mmListTasksByJob.mock.funcListTasksByJob != nil {
		mmListTasksByJob.mock.t.Fatalf("CrawlTaskServiceMock.ListTasksByJob mock is already set by Set")
	}

	if mmListTasksByJob.defaultExpectation == nil {
		mmListTasksByJob.defaultExpectation = &CrawlTaskServiceMockListTasksByJobExpectation{}
	}

	if mmListTasksByJob.defaultExpectation.params != nil {
		mmListTasksByJob.mock.t.Fatalf("CrawlTaskServiceMock.ListTasksByJob mock is already set by Expect")
	}

	if mmListTasksByJob.defaultExpectation.paramPtrs == nil {
		mmListTasksByJob.defaultExpectation.paramPtrs = &CrawlTaskServiceMockListTasksByJobParamPtrs{}
	}
	mmListTasksByJob.defaultExpectation.paramPtrs.query = &query
	mmListTasksByJob.defaultExpectation.expectationOrigins.originQuery = minimock.CallerInfo(1)

	return mmListTasksByJob
}

// Inspect accepts an inspector function that has same arguments as the CrawlTaskService.ListTasksByJob
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) Inspect(f func(ctx context.Context, query mm_service.ListTasksByJobQuery)) *mCrawlTaskServiceMockListTasksByJob {
	if mmListTasksByJob.mock.inspectFuncListTasksByJob != nil {
		mmListTasksByJob.mock.t.Fatalf("Inspect function is already set for CrawlTaskServiceMock.ListTasksByJob")
	}

	mmListTasksByJob.mock.inspectFuncListTasksByJob = f

	return mmListTasksByJob
}

// Return sets up results that will be returned by CrawlTaskService.ListTasksByJob
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) Return(cpa1 []*models.CrawlTask, err error) *CrawlTaskServiceMock {
	if mmListTasksByJob.mock.funcListTasksByJob != nil {
		mmListTasksByJob.mock.t.Fatalf("CrawlTaskServiceMock.ListTasksByJob mock is already set by Set")
	}

	if mmListTasksByJob.defaultExpectation == nil {
		mmListTasksByJob.defaultExpectation = &CrawlTaskServiceMockListTasksByJobExpectation{mock: mmListTasksByJob.mock}
	}
	mmListTasksByJob.defaultExpectation.results = &CrawlTaskServiceMockListTasksByJobResults{cpa1, err}
	mmListTasksByJob.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListTasksByJob.mock
}

// Set uses given function f to mock the CrawlTaskService.ListTasksByJob method
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) Set(f func(ctx context.Context, query mm_service.ListTasksByJobQuery) (cpa1 []*models.CrawlTask, err error)) *CrawlTaskServiceMock {
	if mmListTasksByJob.defaultExpectation != nil {
		mmListTasksByJob.mock.t.Fatalf("Default expectation is already set for the CrawlTaskService.ListTasksByJob method")
	}

	if len(mmListTasksByJob.expectations) > 0 {
		mmListTasksByJob.mock.t.Fatalf("Some expectations are already set for the CrawlTaskService.ListTasksByJob method")
	}

	mmListTasksByJob.mock.funcListTasksByJob = f
	mmListTasksByJob.mock.funcListTasksByJobOrigin = minimock.CallerInfo(1)
	return mmListTasksByJob.mock
}

// When sets expectation for the CrawlTaskService.ListTasksByJob which will trigger the result defined by the following
// Then helper
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) When(ctx context.Context, query mm_service.ListTasksByJobQuery) *CrawlTaskServiceMockListTasksByJobExpectation {
	if mmListTasksByJob.mock.funcListTasksByJob != nil {
		mmListTasksByJob.mock.t.Fatalf("CrawlTaskServiceMock.ListTasksByJob mock is already set by Set")
	}

	expectation := &CrawlTaskServiceMockListTasksByJobExpectation{
		mock:               mmListTasksByJob.mock,
		params:             &CrawlTaskServiceMockListTasksByJobParams{ctx, query},
		expectationOrigins: CrawlTaskServiceMockListTasksByJobExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListTasksByJob.expectations = append(mmListTasksByJob.expectations, expectation)
	return expectation
}

// Then sets up CrawlTaskService.ListTasksByJob return parameters for the expectation previously defined by the When method
func (e *CrawlTaskServiceMockListTasksByJobExpectation) Then(cpa1 []*models.CrawlTask, err error) *CrawlTaskServiceMock {
	e.results = &CrawlTaskServiceMockListTasksByJobResults{cpa1, err}
	return e.mock
}

// Times sets number of times CrawlTaskService.ListTasksByJob should be invoked
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) Times(n uint64) *mCrawlTaskServiceMockListTasksByJob {
	if n == 0 {
		mmListTasksByJob.mock.t.Fatalf("Times of CrawlTaskServiceMock.ListTasksByJob mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListTasksByJob.expectedInvocations, n)
	mmListTasksByJob.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListTasksByJob
}

func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) invocationsDone() bool {
	if len(mmListTasksByJob.expectations) == 0 && mmListTasksByJob.defaultExpectation == nil && mmListTasksByJob.mock.funcListTasksByJob == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListTasksByJob.mock.afterListTasksByJobCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListTasksByJob.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListTasksByJob implements mm_service.CrawlTaskService
func (mmListTasksByJob *CrawlTaskServiceMock) ListTasksByJob(ctx context.Context, query mm_service.ListTasksByJobQuery) (cpa1 []*models.CrawlTask, err error) {
	mm_atomic.AddUint64(&mmListTasksByJob.beforeListTasksByJobCounter, 1)
	defer mm_atomic.AddUint64(&mmListTasksByJob.afterListTasksByJobCounter, 1)

	mmListTasksByJob.t.Helper()

	if mmListTasksByJob.inspectFuncListTasksByJob != nil {
		mmListTasksByJob.inspectFuncListTasksByJob(ctx, query)
	}

	mm_params := CrawlTaskServiceMockListTasksByJobParams{ctx, query}

	// Record call args
	mmListTasksByJob.ListTasksByJobMock.mutex.Lock()
	mmListTasksByJob.ListTasksByJobMock.callArgs = append(mmListTasksByJob.ListTasksByJobMock.callArgs, &mm_params)
	mmListTasksByJob.ListTasksByJobMock.mutex.Unlock()

	for _, e := range mmListTasksByJob.ListTasksByJobMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cpa1, e.results.err
		}
	}

	if mmListTasksByJob.ListTasksByJobMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListTasksByJob.ListTasksByJobMock.defaultExpectation.Counter, 1)
		mm_want := mmListTasksByJob.ListTasksByJobMock.defaultExpectation.params
		mm_want_ptrs := mmListTasksByJob.ListTasksByJobMock.defaultExpectation.paramPtrs

		mm_got := CrawlTaskServiceMockListTasksByJobParams{ctx, query}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListTasksByJob.t.Errorf("CrawlTaskServiceMock.ListTasksByJob got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListTasksByJob.ListTasksByJobMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.query != nil && !minimock.Equal(*mm_want_ptrs.query, mm_got.query) {
				mmListTasksByJob.t.Errorf("CrawlTaskServiceMock.ListTasksByJob got unexpected parameter query, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListTasksByJob.ListTasksByJobMock.defaultExpectation.expectationOrigins.originQuery, *mm_want_ptrs.query, mm_got.query, minimock.Diff(*mm_want_ptrs.query, mm_got.query))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListTasksByJob.t.Errorf("CrawlTaskServiceMock.ListTasksByJob got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListTasksByJob.ListTasksByJobMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListTasksByJob.ListTasksByJobMock.defaultExpectation.results
		if mm_results == nil {
			mmListTasksByJob.t.Fatal("No results are set for the CrawlTaskServiceMock.ListTasksByJob")
		}
		return (*mm_results).cpa1, (*mm_results).err
	}
	if mmListTasksByJob.funcListTasksByJob != nil {
		return mmListTasksByJob.funcListTasksByJob(ctx, query)
	}
	mmListTasksByJob.t.Fatalf("Unexpected call to CrawlTaskServiceMock.ListTasksByJob. %v %v", ctx, query)
	return
}

// ListTasksByJobAfterCounter returns a count of finished CrawlTaskServiceMock.ListTasksByJob invocations
func (mmListTasksByJob *CrawlTaskServiceMock) ListTasksByJobAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListTasksByJob.afterListTasksByJobCounter)
}

// ListTasksByJobBeforeCounter returns a count of CrawlTaskServiceMock.ListTasksByJob invocations
func (mmListTasksByJob *CrawlTaskServiceMock) ListTasksByJobBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListTasksByJob.beforeListTasksByJobCounter)
}

// Calls returns a list of arguments used in each call to CrawlTaskServiceMock.ListTasksByJob.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListTasksByJob *mCrawlTaskServiceMockListTasksByJob) Calls() []*CrawlTaskServiceMockListTasksByJobParams {
	mmListTasksByJob.mutex.RLock()

	argCopy := make([]*CrawlTaskServiceMockListTasksByJobParams, len(mmListTasksByJob.callArgs))
	copy(argCopy, mmListTasksByJob.callArgs)

	mmListTasksByJob.mutex.RUnlock()

	return argCopy
}

// MinimockListTasksByJobDone returns true if the count of the ListTasksByJob invocations corresponds
// the number of defined expectations
func (m *CrawlTaskServiceMock) MinimockListTasksByJobDone() bool {
	if m.ListTasksByJobMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListTasksByJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListTasksByJobMock.invocationsDone()
}

// MinimockListTasksByJobInspect logs each unmet expectation
func (m *CrawlTaskServiceMock) MinimockListTasksByJobInspect() {
	for _, e := range m.ListTasksByJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.ListTasksByJob at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListTasksByJobCounter := mm_atomic.LoadUint64(&m.afterListTasksByJobCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListTasksByJobMock.defaultExpectation != nil && afterListTasksByJobCounter < 1 {
		if m.ListTasksByJobMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.ListTasksByJob at\n%s", m.ListTasksByJobMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.ListTasksByJob at\n%s with params: %#v", m.ListTasksByJobMock.defaultExpectation.expectationOrigins.origin, *m.ListTasksByJobMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListTasksByJob != nil && afterListTasksByJobCounter < 1 {
		m.t.Errorf("Expected call to CrawlTaskServiceMock.ListTasksByJob at\n%s", m.funcListTasksByJobOrigin)
	}

	if !m.ListTasksByJobMock.invocationsDone() && afterListTasksByJobCounter > 0 {
		m.t.Errorf("Expected %d calls to CrawlTaskServiceMock.ListTasksByJob at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListTasksByJobMock.expectedInvocations), m.ListTasksByJobMock.expectedInvocationsOrigin, afterListTasksByJobCounter)
	}
}

type mCrawlTaskServiceMockUpdateTaskStatus struct {
	optional           bool
	mock               *CrawlTaskServiceMock
	defaultExpectation *CrawlTaskServiceMockUpdateTaskStatusExpectation
	expectations       []*CrawlTaskServiceMockUpdateTaskStatusExpectation

	callArgs []*CrawlTaskServiceMockUpdateTaskStatusParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CrawlTaskServiceMockUpdateTaskStatusExpectation specifies expectation struct of the CrawlTaskService.UpdateTaskStatus
type CrawlTaskServiceMockUpdateTaskStatusExpectation struct {
	mock               *CrawlTaskServiceMock
	params             *CrawlTaskServiceMockUpdateTaskStatusParams
	paramPtrs          *CrawlTaskServiceMockUpdateTaskStatusParamPtrs
	expectationOrigins CrawlTaskServiceMockUpdateTaskStatusExpectationOrigins
	results            *CrawlTaskServiceMockUpdateTaskStatusResults
	returnOrigin       string
	Counter            uint64
}

// CrawlTaskServiceMockUpdateTaskStatusParams contains parameters of the CrawlTaskService.UpdateTaskStatus
type CrawlTaskServiceMockUpdateTaskStatusParams struct {
	ctx context.Context
	cmd mm_service.UpdateTaskStatusCommand
}

// CrawlTaskServiceMockUpdateTaskStatusParamPtrs contains pointers to parameters of the CrawlTaskService.UpdateTaskStatus
type CrawlTaskServiceMockUpdateTaskStatusParamPtrs struct {
	ctx *context.Context
	cmd *mm_service.UpdateTaskStatusCommand
}

// CrawlTaskServiceMockUpdateTaskStatusResults contains results of the CrawlTaskService.UpdateTaskStatus
type CrawlTaskServiceMockUpdateTaskStatusResults struct {
	err error
}

// CrawlTaskServiceMockUpdateTaskStatusOrigins contains origins of expectations of the CrawlTaskService.UpdateTaskStatus
type CrawlTaskServiceMockUpdateTaskStatusExpectationOrigins struct {
	origin    string
	originCtx string
	originCmd string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) Optional() *mCrawlTaskServiceMockUpdateTaskStatus {
	mmUpdateTaskStatus.optional = true
	return mmUpdateTaskStatus
}

// Expect sets up expected params for CrawlTaskService.UpdateTaskStatus
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) Expect(ctx context.Context, cmd mm_service.UpdateTaskStatusCommand) *mCrawlTaskServiceMockUpdateTaskStatus {
	if mmUpdateTaskStatus.mock.funcUpdateTaskStatus != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("CrawlTaskServiceMock.UpdateTaskStatus mock is already set by Set")
	}

	if mmUpdateTaskStatus.defaultExpectation == nil {
		mmUpdateTaskStatus.defaultExpectation = &CrawlTaskServiceMockUpdateTaskStatusExpectation{}
	}

	if mmUpdateTaskStatus.defaultExpectation.paramPtrs != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("CrawlTaskServiceMock.UpdateTaskStatus mock is already set by ExpectParams functions")
	}

	mmUpdateTaskStatus.defaultExpectation.params = &CrawlTaskServiceMockUpdateTaskStatusParams{ctx, cmd}
	mmUpdateTaskStatus.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateTaskStatus.expectations {
		if minimock.Equal(e.params, mmUpdateTaskStatus.defaultExpectation.params) {
			mmUpdateTaskStatus.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateTaskStatus.defaultExpectation.params)
		}
	}

	return mmUpdateTaskStatus
}

// ExpectCtxParam1 sets up expected param ctx for CrawlTaskService.UpdateTaskStatus
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) ExpectCtxParam1(ctx context.Context) *mCrawlTaskServiceMockUpdateTaskStatus {
	if mmUpdateTaskStatus.mock.funcUpdateTaskStatus != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("CrawlTaskServiceMock.UpdateTaskStatus mock is already set by Set")
	}

	if mmUpdateTaskStatus.defaultExpectation == nil {
		mmUpdateTaskStatus.defaultExpectation = &CrawlTaskServiceMockUpdateTaskStatusExpectation{}
	}

	if mmUpdateTaskStatus.defaultExpectation.params != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("CrawlTaskServiceMock.UpdateTaskStatus mock is already set by Expect")
	}

	if mmUpdateTaskStatus.defaultExpectation.paramPtrs == nil {
		mmUpdateTaskStatus.defaultExpectation.paramPtrs = &CrawlTaskServiceMockUpdateTaskStatusParamPtrs{}
	}
	mmUpdateTaskStatus.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateTaskStatus.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateTaskStatus
}

// ExpectCmdParam2 sets up expected param cmd for CrawlTaskService.UpdateTaskStatus
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) ExpectCmdParam2(cmd mm_service.UpdateTaskStatusCommand) *mCrawlTaskServiceMockUpdateTaskStatus {
	if mmUpdateTaskStatus.mock.funcUpdateTaskStatus != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("CrawlTaskServiceMock.UpdateTaskStatus mock is already set by Set")
	}

	if mmUpdateTaskStatus.defaultExpectation == nil {
		mmUpdateTaskStatus.defaultExpectation = &CrawlTaskServiceMockUpdateTaskStatusExpectation{}
	}

	if mmUpdateTaskStatus.defaultExpectation.params != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("CrawlTaskServiceMock.UpdateTaskStatus mock is already set by Expect")
	}

	if mmUpdateTaskStatus.defaultExpectation.paramPtrs == nil {
		mmUpdateTaskStatus.defaultExpectation.paramPtrs = &CrawlTaskServiceMockUpdateTaskStatusParamPtrs{}
	}
	mmUpdateTaskStatus.defaultExpectation.paramPtrs.cmd = &cmd
	mmUpdateTaskStatus.defaultExpectation.expectationOrigins.originCmd = minimock.CallerInfo(1)

	return mmUpdateTaskStatus
}

// Inspect accepts an inspector function that has same arguments as the CrawlTaskService.UpdateTaskStatus
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) Inspect(f func(ctx context.Context, cmd mm_service.UpdateTaskStatusCommand)) *mCrawlTaskServiceMockUpdateTaskStatus {
	if mmUpdateTaskStatus.mock.inspectFuncUpdateTaskStatus != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("Inspect function is already set for CrawlTaskServiceMock.UpdateTaskStatus")
	}

	mmUpdateTaskStatus.mock.inspectFuncUpdateTaskStatus = f

	return mmUpdateTaskStatus
}

// Return sets up results that will be returned by CrawlTaskService.UpdateTaskStatus
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) Return(err error) *CrawlTaskServiceMock {
	if mmUpdateTaskStatus.mock.funcUpdateTaskStatus != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("CrawlTaskServiceMock.UpdateTaskStatus mock is already set by Set")
	}

	if mmUpdateTaskStatus.defaultExpectation == nil {
		mmUpdateTaskStatus.defaultExpectation = &CrawlTaskServiceMockUpdateTaskStatusExpectation{mock: mmUpdateTaskStatus.mock}
	}
	mmUpdateTaskStatus.defaultExpectation.results = &CrawlTaskServiceMockUpdateTaskStatusResults{err}
	mmUpdateTaskStatus.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateTaskStatus.mock
}

// Set uses given function f to mock the CrawlTaskService.UpdateTaskStatus method
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) Set(f func(ctx context.Context, cmd mm_service.UpdateTaskStatusCommand) (err error)) *CrawlTaskServiceMock {
	if mmUpdateTaskStatus.defaultExpectation != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("Default expectation is already set for the CrawlTaskService.UpdateTaskStatus method")
	}

	if len(mmUpdateTaskStatus.expectations) > 0 {
		mmUpdateTaskStatus.mock.t.Fatalf("Some expectations are already set for the CrawlTaskService.UpdateTaskStatus method")
	}

	mmUpdateTaskStatus.mock.funcUpdateTaskStatus = f
	mmUpdateTaskStatus.mock.funcUpdateTaskStatusOrigin = minimock.CallerInfo(1)
	return mmUpdateTaskStatus.mock
}

// When sets expectation for the CrawlTaskService.UpdateTaskStatus which will trigger the result defined by the following
// Then helper
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) When(ctx context.Context, cmd mm_service.UpdateTaskStatusCommand) *CrawlTaskServiceMockUpdateTaskStatusExpectation {
	if mmUpdateTaskStatus.mock.funcUpdateTaskStatus != nil {
		mmUpdateTaskStatus.mock.t.Fatalf("CrawlTaskServiceMock.UpdateTaskStatus mock is already set by Set")
	}

	expectation := &CrawlTaskServiceMockUpdateTaskStatusExpectation{
		mock:               mmUpdateTaskStatus.mock,
		params:             &CrawlTaskServiceMockUpdateTaskStatusParams{ctx, cmd},
		expectationOrigins: CrawlTaskServiceMockUpdateTaskStatusExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateTaskStatus.expectations = append(mmUpdateTaskStatus.expectations, expectation)
	return expectation
}

// Then sets up CrawlTaskService.UpdateTaskStatus return parameters for the expectation previously defined by the When method
func (e *CrawlTaskServiceMockUpdateTaskStatusExpectation) Then(err error) *CrawlTaskServiceMock {
	e.results = &CrawlTaskServiceMockUpdateTaskStatusResults{err}
	return e.mock
}

// Times sets number of times CrawlTaskService.UpdateTaskStatus should be invoked
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) Times(n uint64) *mCrawlTaskServiceMockUpdateTaskStatus {
	if n == 0 {
		mmUpdateTaskStatus.mock.t.Fatalf("Times of CrawlTaskServiceMock.UpdateTaskStatus mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateTaskStatus.expectedInvocations, n)
	mmUpdateTaskStatus.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateTaskStatus
}

func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) invocationsDone() bool {
	if len(mmUpdateTaskStatus.expectations) == 0 && mmUpdateTaskStatus.defaultExpectation == nil && mmUpdateTaskStatus.mock.funcUpdateTaskStatus == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateTaskStatus.mock.afterUpdateTaskStatusCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateTaskStatus.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateTaskStatus implements mm_service.CrawlTaskService
func (mmUpdateTaskStatus *CrawlTaskServiceMock) UpdateTaskStatus(ctx context.Context, cmd mm_service.UpdateTaskStatusCommand) (err error) {
	mm_atomic.AddUint64(&mmUpdateTaskStatus.beforeUpdateTaskStatusCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateTaskStatus.afterUpdateTaskStatusCounter, 1)

	mmUpdateTaskStatus.t.Helper()

	if mmUpdateTaskStatus.inspectFuncUpdateTaskStatus != nil {
		mmUpdateTaskStatus.inspectFuncUpdateTaskStatus(ctx, cmd)
	}

	mm_params := CrawlTaskServiceMockUpdateTaskStatusParams{ctx, cmd}

	// Record call args
	mmUpdateTaskStatus.UpdateTaskStatusMock.mutex.Lock()
	mmUpdateTaskStatus.UpdateTaskStatusMock.callArgs = append(mmUpdateTaskStatus.UpdateTaskStatusMock.callArgs, &mm_params)
	mmUpdateTaskStatus.UpdateTaskStatusMock.mutex.Unlock()

	for _, e := range mmUpdateTaskStatus.UpdateTaskStatusMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateTaskStatus.UpdateTaskStatusMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateTaskStatus.UpdateTaskStatusMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateTaskStatus.UpdateTaskStatusMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateTaskStatus.UpdateTaskStatusMock.defaultExpectation.paramPtrs

		mm_got := CrawlTaskServiceMockUpdateTaskStatusParams{ctx, cmd}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateTaskStatus.t.Errorf("CrawlTaskServiceMock.UpdateTaskStatus got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateTaskStatus.UpdateTaskStatusMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.cmd != nil && !minimock.Equal(*mm_want_ptrs.cmd, mm_got.cmd) {
				mmUpdateTaskStatus.t.Errorf("CrawlTaskServiceMock.UpdateTaskStatus got unexpected parameter cmd, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateTaskStatus.UpdateTaskStatusMock.defaultExpectation.expectationOrigins.originCmd, *mm_want_ptrs.cmd, mm_got.cmd, minimock.Diff(*mm_want_ptrs.cmd, mm_got.cmd))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateTaskStatus.t.Errorf("CrawlTaskServiceMock.UpdateTaskStatus got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateTaskStatus.UpdateTaskStatusMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateTaskStatus.UpdateTaskStatusMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateTaskStatus.t.Fatal("No results are set for the CrawlTaskServiceMock.UpdateTaskStatus")
		}
		return (*mm_results).err
	}
	if mmUpdateTaskStatus.funcUpdateTaskStatus != nil {
		return mmUpdateTaskStatus.funcUpdateTaskStatus(ctx, cmd)
	}
	mmUpdateTaskStatus.t.Fatalf("Unexpected call to CrawlTaskServiceMock.UpdateTaskStatus. %v %v", ctx, cmd)
	return
}

// UpdateTaskStatusAfterCounter returns a count of finished CrawlTaskServiceMock.UpdateTaskStatus invocations
func (mmUpdateTaskStatus *CrawlTaskServiceMock) UpdateTaskStatusAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateTaskStatus.afterUpdateTaskStatusCounter)
}

// UpdateTaskStatusBeforeCounter returns a count of CrawlTaskServiceMock.UpdateTaskStatus invocations
func (mmUpdateTaskStatus *CrawlTaskServiceMock) UpdateTaskStatusBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateTaskStatus.beforeUpdateTaskStatusCounter)
}

// Calls returns a list of arguments used in each call to CrawlTaskServiceMock.UpdateTaskStatus.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateTaskStatus *mCrawlTaskServiceMockUpdateTaskStatus) Calls() []*CrawlTaskServiceMockUpdateTaskStatusParams {
	mmUpdateTaskStatus.mutex.RLock()

	argCopy := make([]*CrawlTaskServiceMockUpdateTaskStatusParams, len(mmUpdateTaskStatus.callArgs))
	copy(argCopy, mmUpdateTaskStatus.callArgs)

	mmUpdateTaskStatus.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateTaskStatusDone returns true if the count of the UpdateTaskStatus invocations corresponds
// the number of defined expectations
func (m *CrawlTaskServiceMock) MinimockUpdateTaskStatusDone() bool {
	if m.UpdateTaskStatusMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateTaskStatusMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateTaskStatusMock.invocationsDone()
}

// MinimockUpdateTaskStatusInspect logs each unmet expectation
func (m *CrawlTaskServiceMock) MinimockUpdateTaskStatusInspect() {
	for _, e := range m.UpdateTaskStatusMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.UpdateTaskStatus at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateTaskStatusCounter := mm_atomic.LoadUint64(&m.afterUpdateTaskStatusCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateTaskStatusMock.defaultExpectation != nil && afterUpdateTaskStatusCounter < 1 {
		if m.UpdateTaskStatusMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.UpdateTaskStatus at\n%s", m.UpdateTaskStatusMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CrawlTaskServiceMock.UpdateTaskStatus at\n%s with params: %#v", m.UpdateTaskStatusMock.defaultExpectation.expectationOrigins.origin, *m.UpdateTaskStatusMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateTaskStatus != nil && afterUpdateTaskStatusCounter < 1 {
		m.t.Errorf("Expected call to CrawlTaskServiceMock.UpdateTaskStatus at\n%s", m.funcUpdateTaskStatusOrigin)
	}

	if !m.UpdateTaskStatusMock.invocationsDone() && afterUpdateTaskStatusCounter > 0 {
		m.t.Errorf("Expected %d calls to CrawlTaskServiceMock.UpdateTaskStatus at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateTaskStatusMock.expectedInvocations), m.UpdateTaskStatusMock.expectedInvocationsOrigin, afterUpdateTaskStatusCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CrawlTaskServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateTaskInspect()

			m.MinimockGetTaskInspect()

			m.MinimockListTasksByJobInspect()

			m.MinimockUpdateTaskStatusInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CrawlTaskServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CrawlTaskServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateTaskDone() &&
		m.MinimockGetTaskDone() &&
		m.MinimockListTasksByJobDone() &&
		m.MinimockUpdateTaskStatusDone()
}
