// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package mocks

//go:generate minimock -i distributed-crawler/internal/application/service.CrawlJobService -o crawl_job_service_minimock.go -n CrawlJobServiceMock -p mocks

import (
	"context"
	mm_service "distributed-crawler/internal/application/service"
	"distributed-crawler/internal/domain/crawl/models"
	"distributed-crawler/internal/domain/crawl/valueobjects"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// CrawlJobServiceMock implements mm_service.CrawlJobService
type CrawlJobServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateCrawlJob          func(ctx context.Context, cmd mm_service.CreateCrawlJobCommand) (c2 valueobjects.CrawlJobID, err error)
	funcCreateCrawlJobOrigin    string
	inspectFuncCreateCrawlJob   func(ctx context.Context, cmd mm_service.CreateCrawlJobCommand)
	afterCreateCrawlJobCounter  uint64
	beforeCreateCrawlJobCounter uint64
	CreateCrawlJobMock          mCrawlJobServiceMockCreateCrawlJob

	funcGetCrawlJob          func(ctx context.Context, query mm_service.GetCrawlJobQuery) (cp1 *models.CrawlJob, err error)
	funcGetCrawlJobOrigin    string
	inspectFuncGetCrawlJob   func(ctx context.Context, query mm_service.GetCrawlJobQuery)
	afterGetCrawlJobCounter  uint64
	beforeGetCrawlJobCounter uint64
	GetCrawlJobMock          mCrawlJobServiceMockGetCrawlJob
}

// NewCrawlJobServiceMock returns a mock for mm_service.CrawlJobService
func NewCrawlJobServiceMock(t minimock.Tester) *CrawlJobServiceMock {
	m := &CrawlJobServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateCrawlJobMock = mCrawlJobServiceMockCreateCrawlJob{mock: m}
	m.CreateCrawlJobMock.callArgs = []*CrawlJobServiceMockCreateCrawlJobParams{}

	m.GetCrawlJobMock = mCrawlJobServiceMockGetCrawlJob{mock: m}
	m.GetCrawlJobMock.callArgs = []*CrawlJobServiceMockGetCrawlJobParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCrawlJobServiceMockCreateCrawlJob struct {
	optional           bool
	mock               *CrawlJobServiceMock
	defaultExpectation *CrawlJobServiceMockCreateCrawlJobExpectation
	expectations       []*CrawlJobServiceMockCreateCrawlJobExpectation

	callArgs []*CrawlJobServiceMockCreateCrawlJobParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CrawlJobServiceMockCreateCrawlJobExpectation specifies expectation struct of the CrawlJobService.CreateCrawlJob
type CrawlJobServiceMockCreateCrawlJobExpectation struct {
	mock               *CrawlJobServiceMock
	params             *CrawlJobServiceMockCreateCrawlJobParams
	paramPtrs          *CrawlJobServiceMockCreateCrawlJobParamPtrs
	expectationOrigins CrawlJobServiceMockCreateCrawlJobExpectationOrigins
	results            *CrawlJobServiceMockCreateCrawlJobResults
	returnOrigin       string
	Counter            uint64
}

// CrawlJobServiceMockCreateCrawlJobParams contains parameters of the CrawlJobService.CreateCrawlJob
type CrawlJobServiceMockCreateCrawlJobParams struct {
	ctx context.Context
	cmd mm_service.CreateCrawlJobCommand
}

// CrawlJobServiceMockCreateCrawlJobParamPtrs contains pointers to parameters of the CrawlJobService.CreateCrawlJob
type CrawlJobServiceMockCreateCrawlJobParamPtrs struct {
	ctx *context.Context
	cmd *mm_service.CreateCrawlJobCommand
}

// CrawlJobServiceMockCreateCrawlJobResults contains results of the CrawlJobService.CreateCrawlJob
type CrawlJobServiceMockCreateCrawlJobResults struct {
	c2  valueobjects.CrawlJobID
	err error
}

// CrawlJobServiceMockCreateCrawlJobOrigins contains origins of expectations of the CrawlJobService.CreateCrawlJob
type CrawlJobServiceMockCreateCrawlJobExpectationOrigins struct {
	origin    string
	originCtx string
	originCmd string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) Optional() *mCrawlJobServiceMockCreateCrawlJob {
	mmCreateCrawlJob.optional = true
	return mmCreateCrawlJob
}

// Expect sets up expected params for CrawlJobService.CreateCrawlJob
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) Expect(ctx context.Context, cmd mm_service.CreateCrawlJobCommand) *mCrawlJobServiceMockCreateCrawlJob {
	if mmCreateCrawlJob.mock.funcCreateCrawlJob != nil {
		mmCreateCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.CreateCrawlJob mock is already set by Set")
	}

	if mmCreateCrawlJob.defaultExpectation == nil {
		mmCreateCrawlJob.defaultExpectation = &CrawlJobServiceMockCreateCrawlJobExpectation{}
	}

	if mmCreateCrawlJob.defaultExpectation.paramPtrs != nil {
		mmCreateCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.CreateCrawlJob mock is already set by ExpectParams functions")
	}

	mmCreateCrawlJob.defaultExpectation.params = &CrawlJobServiceMockCreateCrawlJobParams{ctx, cmd}
	mmCreateCrawlJob.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateCrawlJob.expectations {
		if minimock.Equal(e.params, mmCreateCrawlJob.defaultExpectation.params) {
			mmCreateCrawlJob.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateCrawlJob.defaultExpectation.params)
		}
	}

	return mmCreateCrawlJob
}

// ExpectCtxParam1 sets up expected param ctx for CrawlJobService.CreateCrawlJob
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) ExpectCtxParam1(ctx context.Context) *mCrawlJobServiceMockCreateCrawlJob {
	if mmCreateCrawlJob.mock.funcCreateCrawlJob != nil {
		mmCreateCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.CreateCrawlJob mock is already set by Set")
	}

	if mmCreateCrawlJob.defaultExpectation == nil {
		mmCreateCrawlJob.defaultExpectation = &CrawlJobServiceMockCreateCrawlJobExpectation{}
	}

	if mmCreateCrawlJob.defaultExpectation.params != nil {
		mmCreateCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.CreateCrawlJob mock is already set by Expect")
	}

	if mmCreateCrawlJob.defaultExpectation.paramPtrs == nil {
		mmCreateCrawlJob.defaultExpectation.paramPtrs = &CrawlJobServiceMockCreateCrawlJobParamPtrs{}
	}
	mmCreateCrawlJob.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateCrawlJob.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateCrawlJob
}

// ExpectCmdParam2 sets up expected param cmd for CrawlJobService.CreateCrawlJob
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) ExpectCmdParam2(cmd mm_service.CreateCrawlJobCommand) *mCrawlJobServiceMockCreateCrawlJob {
	if mmCreateCrawlJob.mock.funcCreateCrawlJob != nil {
		mmCreateCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.CreateCrawlJob mock is already set by Set")
	}

	if mmCreateCrawlJob.defaultExpectation == nil {
		mmCreateCrawlJob.defaultExpectation = &CrawlJobServiceMockCreateCrawlJobExpectation{}
	}

	if mmCreateCrawlJob.defaultExpectation.params != nil {
		mmCreateCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.CreateCrawlJob mock is already set by Expect")
	}

	if mmCreateCrawlJob.defaultExpectation.paramPtrs == nil {
		mmCreateCrawlJob.defaultExpectation.paramPtrs = &CrawlJobServiceMockCreateCrawlJobParamPtrs{}
	}
	mmCreateCrawlJob.defaultExpectation.paramPtrs.cmd = &cmd
	mmCreateCrawlJob.defaultExpectation.expectationOrigins.originCmd = minimock.CallerInfo(1)

	return mmCreateCrawlJob
}

// Inspect accepts an inspector function that has same arguments as the CrawlJobService.CreateCrawlJob
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) Inspect(f func(ctx context.Context, cmd mm_service.CreateCrawlJobCommand)) *mCrawlJobServiceMockCreateCrawlJob {
	if mmCreateCrawlJob.mock.inspectFuncCreateCrawlJob != nil {
		mmCreateCrawlJob.mock.t.Fatalf("Inspect function is already set for CrawlJobServiceMock.CreateCrawlJob")
	}

	mmCreateCrawlJob.mock.inspectFuncCreateCrawlJob = f

	return mmCreateCrawlJob
}

// Return sets up results that will be returned by CrawlJobService.CreateCrawlJob
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) Return(c2 valueobjects.CrawlJobID, err error) *CrawlJobServiceMock {
	if mmCreateCrawlJob.mock.funcCreateCrawlJob != nil {
		mmCreateCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.CreateCrawlJob mock is already set by Set")
	}

	if mmCreateCrawlJob.defaultExpectation == nil {
		mmCreateCrawlJob.defaultExpectation = &CrawlJobServiceMockCreateCrawlJobExpectation{mock: mmCreateCrawlJob.mock}
	}
	mmCreateCrawlJob.defaultExpectation.results = &CrawlJobServiceMockCreateCrawlJobResults{c2, err}
	mmCreateCrawlJob.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateCrawlJob.mock
}

// Set uses given function f to mock the CrawlJobService.CreateCrawlJob method
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) Set(f func(ctx context.Context, cmd mm_service.CreateCrawlJobCommand) (c2 valueobjects.CrawlJobID, err error)) *CrawlJobServiceMock {
	if mmCreateCrawlJob.defaultExpectation != nil {
		mmCreateCrawlJob.mock.t.Fatalf("Default expectation is already set for the CrawlJobService.CreateCrawlJob method")
	}

	if len(mmCreateCrawlJob.expectations) > 0 {
		mmCreateCrawlJob.mock.t.Fatalf("Some expectations are already set for the CrawlJobService.CreateCrawlJob method")
	}

	mmCreateCrawlJob.mock.funcCreateCrawlJob = f
	mmCreateCrawlJob.mock.funcCreateCrawlJobOrigin = minimock.CallerInfo(1)
	return mmCreateCrawlJob.mock
}

// When sets expectation for the CrawlJobService.CreateCrawlJob which will trigger the result defined by the following
// Then helper
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) When(ctx context.Context, cmd mm_service.CreateCrawlJobCommand) *CrawlJobServiceMockCreateCrawlJobExpectation {
	if mmCreateCrawlJob.mock.funcCreateCrawlJob != nil {
		mmCreateCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.CreateCrawlJob mock is already set by Set")
	}

	expectation := &CrawlJobServiceMockCreateCrawlJobExpectation{
		mock:               mmCreateCrawlJob.mock,
		params:             &CrawlJobServiceMockCreateCrawlJobParams{ctx, cmd},
		expectationOrigins: CrawlJobServiceMockCreateCrawlJobExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateCrawlJob.expectations = append(mmCreateCrawlJob.expectations, expectation)
	return expectation
}

// Then sets up CrawlJobService.CreateCrawlJob return parameters for the expectation previously defined by the When method
func (e *CrawlJobServiceMockCreateCrawlJobExpectation) Then(c2 valueobjects.CrawlJobID, err error) *CrawlJobServiceMock {
	e.results = &CrawlJobServiceMockCreateCrawlJobResults{c2, err}
	return e.mock
}

// Times sets number of times CrawlJobService.CreateCrawlJob should be invoked
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) Times(n uint64) *mCrawlJobServiceMockCreateCrawlJob {
	if n == 0 {
		mmCreateCrawlJob.mock.t.Fatalf("Times of CrawlJobServiceMock.CreateCrawlJob mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateCrawlJob.expectedInvocations, n)
	mmCreateCrawlJob.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateCrawlJob
}

func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) invocationsDone() bool {
	if len(mmCreateCrawlJob.expectations) == 0 && mmCreateCrawlJob.defaultExpectation == nil && mmCreateCrawlJob.mock.funcCreateCrawlJob == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateCrawlJob.mock.afterCreateCrawlJobCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateCrawlJob.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateCrawlJob implements mm_service.CrawlJobService
func (mmCreateCrawlJob *CrawlJobServiceMock) CreateCrawlJob(ctx context.Context, cmd mm_service.CreateCrawlJobCommand) (c2 valueobjects.CrawlJobID, err error) {
	mm_atomic.AddUint64(&mmCreateCrawlJob.beforeCreateCrawlJobCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateCrawlJob.afterCreateCrawlJobCounter, 1)

	mmCreateCrawlJob.t.Helper()

	if mmCreateCrawlJob.inspectFuncCreateCrawlJob != nil {
		mmCreateCrawlJob.inspectFuncCreateCrawlJob(ctx, cmd)
	}

	mm_params := CrawlJobServiceMockCreateCrawlJobParams{ctx, cmd}

	// Record call args
	mmCreateCrawlJob.CreateCrawlJobMock.mutex.Lock()
	mmCreateCrawlJob.CreateCrawlJobMock.callArgs = append(mmCreateCrawlJob.CreateCrawlJobMock.callArgs, &mm_params)
	mmCreateCrawlJob.CreateCrawlJobMock.mutex.Unlock()

	for _, e := range mmCreateCrawlJob.CreateCrawlJobMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c2, e.results.err
		}
	}

	if mmCreateCrawlJob.CreateCrawlJobMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateCrawlJob.CreateCrawlJobMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateCrawlJob.CreateCrawlJobMock.defaultExpectation.params
		mm_want_ptrs := mmCreateCrawlJob.CreateCrawlJobMock.defaultExpectation.paramPtrs

		mm_got := CrawlJobServiceMockCreateCrawlJobParams{ctx, cmd}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateCrawlJob.t.Errorf("CrawlJobServiceMock.CreateCrawlJob got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateCrawlJob.CreateCrawlJobMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.cmd != nil && !minimock.Equal(*mm_want_ptrs.cmd, mm_got.cmd) {
				mmCreateCrawlJob.t.Errorf("CrawlJobServiceMock.CreateCrawlJob got unexpected parameter cmd, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateCrawlJob.CreateCrawlJobMock.defaultExpectation.expectationOrigins.originCmd, *mm_want_ptrs.cmd, mm_got.cmd, minimock.Diff(*mm_want_ptrs.cmd, mm_got.cmd))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateCrawlJob.t.Errorf("CrawlJobServiceMock.CreateCrawlJob got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateCrawlJob.CreateCrawlJobMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateCrawlJob.CreateCrawlJobMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateCrawlJob.t.Fatal("No results are set for the CrawlJobServiceMock.CreateCrawlJob")
		}
		return (*mm_results).c2, (*mm_results).err
	}
	if mmCreateCrawlJob.funcCreateCrawlJob != nil {
		return mmCreateCrawlJob.funcCreateCrawlJob(ctx, cmd)
	}
	mmCreateCrawlJob.t.Fatalf("Unexpected call to CrawlJobServiceMock.CreateCrawlJob. %v %v", ctx, cmd)
	return
}

// CreateCrawlJobAfterCounter returns a count of finished CrawlJobServiceMock.CreateCrawlJob invocations
func (mmCreateCrawlJob *CrawlJobServiceMock) CreateCrawlJobAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateCrawlJob.afterCreateCrawlJobCounter)
}

// CreateCrawlJobBeforeCounter returns a count of CrawlJobServiceMock.CreateCrawlJob invocations
func (mmCreateCrawlJob *CrawlJobServiceMock) CreateCrawlJobBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateCrawlJob.beforeCreateCrawlJobCounter)
}

// Calls returns a list of arguments used in each call to CrawlJobServiceMock.CreateCrawlJob.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateCrawlJob *mCrawlJobServiceMockCreateCrawlJob) Calls() []*CrawlJobServiceMockCreateCrawlJobParams {
	mmCreateCrawlJob.mutex.RLock()

	argCopy := make([]*CrawlJobServiceMockCreateCrawlJobParams, len(mmCreateCrawlJob.callArgs))
	copy(argCopy, mmCreateCrawlJob.callArgs)

	mmCreateCrawlJob.mutex.RUnlock()

	return argCopy
}

// MinimockCreateCrawlJobDone returns true if the count of the CreateCrawlJob invocations corresponds
// the number of defined expectations
func (m *CrawlJobServiceMock) MinimockCreateCrawlJobDone() bool {
	if m.CreateCrawlJobMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateCrawlJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateCrawlJobMock.invocationsDone()
}

// MinimockCreateCrawlJobInspect logs each unmet expectation
func (m *CrawlJobServiceMock) MinimockCreateCrawlJobInspect() {
	for _, e := range m.CreateCrawlJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CrawlJobServiceMock.CreateCrawlJob at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCrawlJobCounter := mm_atomic.LoadUint64(&m.afterCreateCrawlJobCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateCrawlJobMock.defaultExpectation != nil && afterCreateCrawlJobCounter < 1 {
		if m.CreateCrawlJobMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CrawlJobServiceMock.CreateCrawlJob at\n%s", m.CreateCrawlJobMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CrawlJobServiceMock.CreateCrawlJob at\n%s with params: %#v", m.CreateCrawlJobMock.defaultExpectation.expectationOrigins.origin, *m.CreateCrawlJobMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateCrawlJob != nil && afterCreateCrawlJobCounter < 1 {
		m.t.Errorf("Expected call to CrawlJobServiceMock.CreateCrawlJob at\n%s", m.funcCreateCrawlJobOrigin)
	}

	if !m.CreateCrawlJobMock.invocationsDone() && afterCreateCrawlJobCounter > 0 {
		m.t.Errorf("Expected %d calls to CrawlJobServiceMock.CreateCrawlJob at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateCrawlJobMock.expectedInvocations), m.CreateCrawlJobMock.expectedInvocationsOrigin, afterCreateCrawlJobCounter)
	}
}

type mCrawlJobServiceMockGetCrawlJob struct {
	optional           bool
	mock               *CrawlJobServiceMock
	defaultExpectation *CrawlJobServiceMockGetCrawlJobExpectation
	expectations       []*CrawlJobServiceMockGetCrawlJobExpectation

	callArgs []*CrawlJobServiceMockGetCrawlJobParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CrawlJobServiceMockGetCrawlJobExpectation specifies expectation struct of the CrawlJobService.GetCrawlJob
type CrawlJobServiceMockGetCrawlJobExpectation struct {
	mock               *CrawlJobServiceMock
	params             *CrawlJobServiceMockGetCrawlJobParams
	paramPtrs          *CrawlJobServiceMockGetCrawlJobParamPtrs
	expectationOrigins CrawlJobServiceMockGetCrawlJobExpectationOrigins
	results            *CrawlJobServiceMockGetCrawlJobResults
	returnOrigin       string
	Counter            uint64
}

// CrawlJobServiceMockGetCrawlJobParams contains parameters of the CrawlJobService.GetCrawlJob
type CrawlJobServiceMockGetCrawlJobParams struct {
	ctx   context.Context
	query mm_service.GetCrawlJobQuery
}

// CrawlJobServiceMockGetCrawlJobParamPtrs contains pointers to parameters of the CrawlJobService.GetCrawlJob
type CrawlJobServiceMockGetCrawlJobParamPtrs struct {
	ctx   *context.Context
	query *mm_service.GetCrawlJobQuery
}

// CrawlJobServiceMockGetCrawlJobResults contains results of the CrawlJobService.GetCrawlJob
type CrawlJobServiceMockGetCrawlJobResults struct {
	cp1 *models.CrawlJob
	err error
}

// CrawlJobServiceMockGetCrawlJobOrigins contains origins of expectations of the CrawlJobService.GetCrawlJob
type CrawlJobServiceMockGetCrawlJobExpectationOrigins struct {
	origin      string
	originCtx   string
	originQuery string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) Optional() *mCrawlJobServiceMockGetCrawlJob {
	mmGetCrawlJob.optional = true
	return mmGetCrawlJob
}

// Expect sets up expected params for CrawlJobService.GetCrawlJob
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) Expect(ctx context.Context, query mm_service.GetCrawlJobQuery) *mCrawlJobServiceMockGetCrawlJob {
	if mmGetCrawlJob.mock.funcGetCrawlJob != nil {
		mmGetCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.GetCrawlJob mock is already set by Set")
	}

	if mmGetCrawlJob.defaultExpectation == nil {
		mmGetCrawlJob.defaultExpectation = &CrawlJobServiceMockGetCrawlJobExpectation{}
	}

	if mmGetCrawlJob.defaultExpectation.paramPtrs != nil {
		mmGetCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.GetCrawlJob mock is already set by ExpectParams functions")
	}

	mmGetCrawlJob.defaultExpectation.params = &CrawlJobServiceMockGetCrawlJobParams{ctx, query}
	mmGetCrawlJob.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetCrawlJob.expectations {
		if minimock.Equal(e.params, mmGetCrawlJob.defaultExpectation.params) {
			mmGetCrawlJob.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetCrawlJob.defaultExpectation.params)
		}
	}

	return mmGetCrawlJob
}

// ExpectCtxParam1 sets up expected param ctx for CrawlJobService.GetCrawlJob
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) ExpectCtxParam1(ctx context.Context) *mCrawlJobServiceMockGetCrawlJob {
	if mmGetCrawlJob.mock.funcGetCrawlJob != nil {
		mmGetCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.GetCrawlJob mock is already set by Set")
	}

	if mmGetCrawlJob.defaultExpectation == nil {
		mmGetCrawlJob.defaultExpectation = &CrawlJobServiceMockGetCrawlJobExpectation{}
	}

	if mmGetCrawlJob.defaultExpectation.params != nil {
		mmGetCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.GetCrawlJob mock is already set by Expect")
	}

	if mmGetCrawlJob.defaultExpectation.paramPtrs == nil {
		mmGetCrawlJob.defaultExpectation.paramPtrs = &CrawlJobServiceMockGetCrawlJobParamPtrs{}
	}
	mmGetCrawlJob.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetCrawlJob.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetCrawlJob
}

// ExpectQueryParam2 sets up expected param query for CrawlJobService.GetCrawlJob
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) ExpectQueryParam2(query mm_service.GetCrawlJobQuery) *mCrawlJobServiceMockGetCrawlJob {
	if mmGetCrawlJob.mock.funcGetCrawlJob != nil {
		mmGetCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.GetCrawlJob mock is already set by Set")
	}

	if mmGetCrawlJob.defaultExpectation == nil {
		mmGetCrawlJob.defaultExpectation = &CrawlJobServiceMockGetCrawlJobExpectation{}
	}

	if mmGetCrawlJob.defaultExpectation.params != nil {
		mmGetCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.GetCrawlJob mock is already set by Expect")
	}

	if mmGetCrawlJob.defaultExpectation.paramPtrs == nil {
		mmGetCrawlJob.defaultExpectation.paramPtrs = &CrawlJobServiceMockGetCrawlJobParamPtrs{}
	}
	mmGetCrawlJob.defaultExpectation.paramPtrs.query = &query
	mmGetCrawlJob.defaultExpectation.expectationOrigins.originQuery = minimock.CallerInfo(1)

	return mmGetCrawlJob
}

// Inspect accepts an inspector function that has same arguments as the CrawlJobService.GetCrawlJob
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) Inspect(f func(ctx context.Context, query mm_service.GetCrawlJobQuery)) *mCrawlJobServiceMockGetCrawlJob {
	if mmGetCrawlJob.mock.inspectFuncGetCrawlJob != nil {
		mmGetCrawlJob.mock.t.Fatalf("Inspect function is already set for CrawlJobServiceMock.GetCrawlJob")
	}

	mmGetCrawlJob.mock.inspectFuncGetCrawlJob = f

	return mmGetCrawlJob
}

// Return sets up results that will be returned by CrawlJobService.GetCrawlJob
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) Return(cp1 *models.CrawlJob, err error) *CrawlJobServiceMock {
	if mmGetCrawlJob.mock.funcGetCrawlJob != nil {
		mmGetCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.GetCrawlJob mock is already set by Set")
	}

	if mmGetCrawlJob.defaultExpectation == nil {
		mmGetCrawlJob.defaultExpectation = &CrawlJobServiceMockGetCrawlJobExpectation{mock: mmGetCrawlJob.mock}
	}
	mmGetCrawlJob.defaultExpectation.results = &CrawlJobServiceMockGetCrawlJobResults{cp1, err}
	mmGetCrawlJob.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetCrawlJob.mock
}

// Set uses given function f to mock the CrawlJobService.GetCrawlJob method
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) Set(f func(ctx context.Context, query mm_service.GetCrawlJobQuery) (cp1 *models.CrawlJob, err error)) *CrawlJobServiceMock {
	if mmGetCrawlJob.defaultExpectation != nil {
		mmGetCrawlJob.mock.t.Fatalf("Default expectation is already set for the CrawlJobService.GetCrawlJob method")
	}

	if len(mmGetCrawlJob.expectations) > 0 {
		mmGetCrawlJob.mock.t.Fatalf("Some expectations are already set for the CrawlJobService.GetCrawlJob method")
	}

	mmGetCrawlJob.mock.funcGetCrawlJob = f
	mmGetCrawlJob.mock.funcGetCrawlJobOrigin = minimock.CallerInfo(1)
	return mmGetCrawlJob.mock
}

// When sets expectation for the CrawlJobService.GetCrawlJob which will trigger the result defined by the following
// Then helper
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) When(ctx context.Context, query mm_service.GetCrawlJobQuery) *CrawlJobServiceMockGetCrawlJobExpectation {
	if mmGetCrawlJob.mock.funcGetCrawlJob != nil {
		mmGetCrawlJob.mock.t.Fatalf("CrawlJobServiceMock.GetCrawlJob mock is already set by Set")
	}

	expectation := &CrawlJobServiceMockGetCrawlJobExpectation{
		mock:               mmGetCrawlJob.mock,
		params:             &CrawlJobServiceMockGetCrawlJobParams{ctx, query},
		expectationOrigins: CrawlJobServiceMockGetCrawlJobExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetCrawlJob.expectations = append(mmGetCrawlJob.expectations, expectation)
	return expectation
}

// Then sets up CrawlJobService.GetCrawlJob return parameters for the expectation previously defined by the When method
func (e *CrawlJobServiceMockGetCrawlJobExpectation) Then(cp1 *models.CrawlJob, err error) *CrawlJobServiceMock {
	e.results = &CrawlJobServiceMockGetCrawlJobResults{cp1, err}
	return e.mock
}

// Times sets number of times CrawlJobService.GetCrawlJob should be invoked
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) Times(n uint64) *mCrawlJobServiceMockGetCrawlJob {
	if n == 0 {
		mmGetCrawlJob.mock.t.Fatalf("Times of CrawlJobServiceMock.GetCrawlJob mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetCrawlJob.expectedInvocations, n)
	mmGetCrawlJob.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetCrawlJob
}

func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) invocationsDone() bool {
	if len(mmGetCrawlJob.expectations) == 0 && mmGetCrawlJob.defaultExpectation == nil && mmGetCrawlJob.mock.funcGetCrawlJob == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetCrawlJob.mock.afterGetCrawlJobCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetCrawlJob.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetCrawlJob implements mm_service.CrawlJobService
func (mmGetCrawlJob *CrawlJobServiceMock) GetCrawlJob(ctx context.Context, query mm_service.GetCrawlJobQuery) (cp1 *models.CrawlJob, err error) {
	mm_atomic.AddUint64(&mmGetCrawlJob.beforeGetCrawlJobCounter, 1)
	defer mm_atomic.AddUint64(&mmGetCrawlJob.afterGetCrawlJobCounter, 1)

	mmGetCrawlJob.t.Helper()

	if mmGetCrawlJob.inspectFuncGetCrawlJob != nil {
		mmGetCrawlJob.inspectFuncGetCrawlJob(ctx, query)
	}

	mm_params := CrawlJobServiceMockGetCrawlJobParams{ctx, query}

	// Record call args
	mmGetCrawlJob.GetCrawlJobMock.mutex.Lock()
	mmGetCrawlJob.GetCrawlJobMock.callArgs = append(mmGetCrawlJob.GetCrawlJobMock.callArgs, &mm_params)
	mmGetCrawlJob.GetCrawlJobMock.mutex.Unlock()

	for _, e := range mmGetCrawlJob.GetCrawlJobMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmGetCrawlJob.GetCrawlJobMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetCrawlJob.GetCrawlJobMock.defaultExpectation.Counter, 1)
		mm_want := mmGetCrawlJob.GetCrawlJobMock.defaultExpectation.params
		mm_want_ptrs := mmGetCrawlJob.GetCrawlJobMock.defaultExpectation.paramPtrs

		mm_got := CrawlJobServiceMockGetCrawlJobParams{ctx, query}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetCrawlJob.t.Errorf("CrawlJobServiceMock.GetCrawlJob got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetCrawlJob.GetCrawlJobMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.query != nil && !minimock.Equal(*mm_want_ptrs.query, mm_got.query) {
				mmGetCrawlJob.t.Errorf("CrawlJobServiceMock.GetCrawlJob got unexpected parameter query, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetCrawlJob.GetCrawlJobMock.defaultExpectation.expectationOrigins.originQuery, *mm_want_ptrs.query, mm_got.query, minimock.Diff(*mm_want_ptrs.query, mm_got.query))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetCrawlJob.t.Errorf("CrawlJobServiceMock.GetCrawlJob got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetCrawlJob.GetCrawlJobMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetCrawlJob.GetCrawlJobMock.defaultExpectation.results
		if mm_results == nil {
			mmGetCrawlJob.t.Fatal("No results are set for the CrawlJobServiceMock.GetCrawlJob")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmGetCrawlJob.funcGetCrawlJob != nil {
		return mmGetCrawlJob.funcGetCrawlJob(ctx, query)
	}
	mmGetCrawlJob.t.Fatalf("Unexpected call to CrawlJobServiceMock.GetCrawlJob. %v %v", ctx, query)
	return
}

// GetCrawlJobAfterCounter returns a count of finished CrawlJobServiceMock.GetCrawlJob invocations
func (mmGetCrawlJob *CrawlJobServiceMock) GetCrawlJobAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCrawlJob.afterGetCrawlJobCounter)
}

// GetCrawlJobBeforeCounter returns a count of CrawlJobServiceMock.GetCrawlJob invocations
func (mmGetCrawlJob *CrawlJobServiceMock) GetCrawlJobBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCrawlJob.beforeGetCrawlJobCounter)
}

// Calls returns a list of arguments used in each call to CrawlJobServiceMock.GetCrawlJob.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetCrawlJob *mCrawlJobServiceMockGetCrawlJob) Calls() []*CrawlJobServiceMockGetCrawlJobParams {
	mmGetCrawlJob.mutex.RLock()

	argCopy := make([]*CrawlJobServiceMockGetCrawlJobParams, len(mmGetCrawlJob.callArgs))
	copy(argCopy, mmGetCrawlJob.callArgs)

	mmGetCrawlJob.mutex.RUnlock()

	return argCopy
}

// MinimockGetCrawlJobDone returns true if the count of the GetCrawlJob invocations corresponds
// the number of defined expectations
func (m *CrawlJobServiceMock) MinimockGetCrawlJobDone() bool {
	if m.GetCrawlJobMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetCrawlJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetCrawlJobMock.invocationsDone()
}

// MinimockGetCrawlJobInspect logs each unmet expectation
func (m *CrawlJobServiceMock) MinimockGetCrawlJobInspect() {
	for _, e := range m.GetCrawlJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CrawlJobServiceMock.GetCrawlJob at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCrawlJobCounter := mm_atomic.LoadUint64(&m.afterGetCrawlJobCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetCrawlJobMock.defaultExpectation != nil && afterGetCrawlJobCounter < 1 {
		if m.GetCrawlJobMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CrawlJobServiceMock.GetCrawlJob at\n%s", m.GetCrawlJobMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CrawlJobServiceMock.GetCrawlJob at\n%s with params: %#v", m.GetCrawlJobMock.defaultExpectation.expectationOrigins.origin, *m.GetCrawlJobMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetCrawlJob != nil && afterGetCrawlJobCounter < 1 {
		m.t.Errorf("Expected call to CrawlJobServiceMock.GetCrawlJob at\n%s", m.funcGetCrawlJobOrigin)
	}

	if !m.GetCrawlJobMock.invocationsDone() && afterGetCrawlJobCounter > 0 {
		m.t.Errorf("Expected %d calls to CrawlJobServiceMock.GetCrawlJob at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetCrawlJobMock.expectedInvocations), m.GetCrawlJobMock.expectedInvocationsOrigin, afterGetCrawlJobCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CrawlJobServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateCrawlJobInspect()

			m.MinimockGetCrawlJobInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CrawlJobServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CrawlJobServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateCrawlJobDone() &&
		m.MinimockGetCrawlJobDone()
}
