// memory_broker.proto — contract for the in-memory gRPC broker.
// This file is for documentation only; the Go implementation in
// internal/infra/messaging/memory/broker/ is hand-written.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: v1/memory_broker.proto

package crawlergrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryBrokerService_Push_FullMethodName      = "/crawler.v1.MemoryBrokerService/Push"
	MemoryBrokerService_Subscribe_FullMethodName = "/crawler.v1.MemoryBrokerService/Subscribe"
)

// MemoryBrokerServiceClient is the client API for MemoryBrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MemoryBrokerService is a lightweight message broker backed entirely by
// in-memory Go channels. It is a drop-in replacement for RabbitMQ/Kafka
// in development and test environments. All messages are lost on restart.
type MemoryBrokerServiceClient interface {
	// Push delivers a message payload to the named queue.
	Push(ctx context.Context, in *MemoryPushRequest, opts ...grpc.CallOption) (*MemoryPushResponse, error)
	// Subscribe opens a server-side stream that delivers messages from the
	// named queue. The stream runs until the client disconnects or the server
	// shuts down. Messages are delivered at-most-once.
	Subscribe(ctx context.Context, in *MemorySubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MemoryBrokerMessage], error)
}

type memoryBrokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryBrokerServiceClient(cc grpc.ClientConnInterface) MemoryBrokerServiceClient {
	return &memoryBrokerServiceClient{cc}
}

func (c *memoryBrokerServiceClient) Push(ctx context.Context, in *MemoryPushRequest, opts ...grpc.CallOption) (*MemoryPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryPushResponse)
	err := c.cc.Invoke(ctx, MemoryBrokerService_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryBrokerServiceClient) Subscribe(ctx context.Context, in *MemorySubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MemoryBrokerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MemoryBrokerService_ServiceDesc.Streams[0], MemoryBrokerService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MemorySubscribeRequest, MemoryBrokerMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemoryBrokerService_SubscribeClient = grpc.ServerStreamingClient[MemoryBrokerMessage]

// MemoryBrokerServiceServer is the server API for MemoryBrokerService service.
// All implementations must embed UnimplementedMemoryBrokerServiceServer
// for forward compatibility.
//
// MemoryBrokerService is a lightweight message broker backed entirely by
// in-memory Go channels. It is a drop-in replacement for RabbitMQ/Kafka
// in development and test environments. All messages are lost on restart.
type MemoryBrokerServiceServer interface {
	// Push delivers a message payload to the named queue.
	Push(context.Context, *MemoryPushRequest) (*MemoryPushResponse, error)
	// Subscribe opens a server-side stream that delivers messages from the
	// named queue. The stream runs until the client disconnects or the server
	// shuts down. Messages are delivered at-most-once.
	Subscribe(*MemorySubscribeRequest, grpc.ServerStreamingServer[MemoryBrokerMessage]) error
	mustEmbedUnimplementedMemoryBrokerServiceServer()
}

// UnimplementedMemoryBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryBrokerServiceServer struct{}

func (UnimplementedMemoryBrokerServiceServer) Push(context.Context, *MemoryPushRequest) (*MemoryPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedMemoryBrokerServiceServer) Subscribe(*MemorySubscribeRequest, grpc.ServerStreamingServer[MemoryBrokerMessage]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedMemoryBrokerServiceServer) mustEmbedUnimplementedMemoryBrokerServiceServer() {}
func (UnimplementedMemoryBrokerServiceServer) testEmbeddedByValue()                             {}

// UnsafeMemoryBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryBrokerServiceServer will
// result in compilation errors.
type UnsafeMemoryBrokerServiceServer interface {
	mustEmbedUnimplementedMemoryBrokerServiceServer()
}

func RegisterMemoryBrokerServiceServer(s grpc.ServiceRegistrar, srv MemoryBrokerServiceServer) {
	// If the following call panics, it indicates UnimplementedMemoryBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryBrokerService_ServiceDesc, srv)
}

func _MemoryBrokerService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryBrokerServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryBrokerService_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryBrokerServiceServer).Push(ctx, req.(*MemoryPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryBrokerService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MemorySubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MemoryBrokerServiceServer).Subscribe(m, &grpc.GenericServerStream[MemorySubscribeRequest, MemoryBrokerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemoryBrokerService_SubscribeServer = grpc.ServerStreamingServer[MemoryBrokerMessage]

// MemoryBrokerService_ServiceDesc is the grpc.ServiceDesc for MemoryBrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryBrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crawler.v1.MemoryBrokerService",
	HandlerType: (*MemoryBrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _MemoryBrokerService_Push_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _MemoryBrokerService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/memory_broker.proto",
}
