// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/service.proto

package crawlergrpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_service_proto protoreflect.FileDescriptor

const file_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x10v1/service.proto\x12\n" +
	"crawler.v1\x1a\x0fv1/models.proto\x1a\x1cgoogle/api/annotations.proto2\x8f\b\n" +
	"\x0eCrawlerService\x12[\n" +
	"\bListJobs\x12\x1b.crawler.v1.ListJobsRequest\x1a\x1c.crawler.v1.ListJobsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/jobs\x12a\n" +
	"\tCreateJob\x12\x1c.crawler.v1.CreateJobRequest\x1a\x1d.crawler.v1.CreateJobResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/jobs\x12Z\n" +
	"\x06GetJob\x12\x19.crawler.v1.GetJobRequest\x1a\x1a.crawler.v1.GetJobResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/jobs/{id}\x12\x90\x01\n" +
	"\x13GetJobExportFileURL\x12&.crawler.v1.GetJobExportFileURLRequest\x1a'.crawler.v1.GetJobExportFileURLResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/jobs/{job_id}/export-url\x12c\n" +
	"\tDeleteJob\x12\x1c.crawler.v1.DeleteJobRequest\x1a\x1d.crawler.v1.DeleteJobResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/jobs/{id}\x12^\n" +
	"\aGetTask\x12\x1a.crawler.v1.GetTaskRequest\x1a\x1b.crawler.v1.GetTaskResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/tasks/{id}\x12|\n" +
	"\x0eListTasksByJob\x12!.crawler.v1.ListTasksByJobRequest\x1a\".crawler.v1.ListTasksByJobResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/jobs/{job_id}/tasks\x12\x86\x01\n" +
	"\x10GetTaskAnalytics\x12#.crawler.v1.GetTaskAnalyticsRequest\x1a$.crawler.v1.GetTaskAnalyticsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/jobs/{job_id}/analytics\x12\x81\x01\n" +
	"\x0eGetTaskFileURL\x12!.crawler.v1.GetTaskFileURLRequest\x1a\".crawler.v1.GetTaskFileURLResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/tasks/{task_id}/file-url2\xef\x01\n" +
	"\x0ePreviewService\x12q\n" +
	"\rCreatePreview\x12 .crawler.v1.CreatePreviewRequest\x1a!.crawler.v1.CreatePreviewResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/previews\x12j\n" +
	"\n" +
	"GetPreview\x12\x1d.crawler.v1.GetPreviewRequest\x1a\x1e.crawler.v1.GetPreviewResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/previews/{id}2\x99\x03\n" +
	"\vAuthService\x12g\n" +
	"\bRegister\x12\x1b.crawler.v1.RegisterRequest\x1a\x1c.crawler.v1.RegisterResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12[\n" +
	"\x05Login\x12\x18.crawler.v1.LoginRequest\x1a\x19.crawler.v1.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12c\n" +
	"\aRefresh\x12\x1a.crawler.v1.RefreshRequest\x1a\x1b.crawler.v1.RefreshResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12_\n" +
	"\x06Logout\x12\x19.crawler.v1.LogoutRequest\x1a\x1a.crawler.v1.LogoutResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout2\xeb\x01\n" +
	"\vUserService\x12_\n" +
	"\tListUsers\x12\x1c.crawler.v1.ListUsersRequest\x1a\x1d.crawler.v1.ListUsersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12{\n" +
	"\x0eUpdateUserRole\x12!.crawler.v1.UpdateUserRoleRequest\x1a\".crawler.v1.UpdateUserRoleResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/api/v1/users/{id}/role2\xe2\x06\n" +
	"\x11QueueAdminService\x12{\n" +
	"\x12ListQueueEndpoints\x12%.crawler.v1.ListQueueEndpointsRequest\x1a&.crawler.v1.ListQueueEndpointsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/queues\x12\x88\x01\n" +
	"\x13CreateQueueEndpoint\x12&.crawler.v1.CreateQueueEndpointRequest\x1a'.crawler.v1.CreateQueueEndpointResponse\" \x82\xd3\xe4\x93\x02\x1a:\bendpoint\"\x0e/api/v1/queues\x12\x96\x01\n" +
	"\x13UpdateQueueEndpoint\x12&.crawler.v1.UpdateQueueEndpointRequest\x1a'.crawler.v1.UpdateQueueEndpointResponse\".\x82\xd3\xe4\x93\x02(:\bendpoint2\x1c/api/v1/queues/{endpoint.id}\x12\x83\x01\n" +
	"\x13DeleteQueueEndpoint\x12&.crawler.v1.DeleteQueueEndpointRequest\x1a'.crawler.v1.DeleteQueueEndpointResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/queues/{id}\x12\x8b\x01\n" +
	"\x15ListQueueRoutingRules\x12(.crawler.v1.ListQueueRoutingRulesRequest\x1a).crawler.v1.ListQueueRoutingRulesResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/queue-routing\x12\x97\x01\n" +
	"\x17UpsertQueueRoutingRules\x12*.crawler.v1.UpsertQueueRoutingRulesRequest\x1a+.crawler.v1.UpsertQueueRoutingRulesResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x04rule\x1a\x15/api/v1/queue-routing2\xd2\x03\n" +
	"\rWorkerService\x12J\n" +
	"\fWorkerStream\x12\x1b.crawler.v1.WorkerHeartbeat\x1a\x19.crawler.v1.WorkerCommand(\x010\x01\x12g\n" +
	"\vListWorkers\x12\x1e.crawler.v1.ListWorkersRequest\x1a\x1f.crawler.v1.ListWorkersResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/workers\x12|\n" +
	"\vDrainWorker\x12\x1e.crawler.v1.DrainWorkerRequest\x1a\x1f.crawler.v1.DrainWorkerResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/workers/{worker_id}:drain\x12\x8d\x01\n" +
	"\x0fForceKillWorker\x12\".crawler.v1.ForceKillWorkerRequest\x1a#.crawler.v1.ForceKillWorkerResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/workers/{worker_id}:force-killB\x90\x01\n" +
	"\x0ecom.crawler.v1B\fServiceProtoP\x01Z'distributed-crawler/pkg/api/crawlergrpc\xa2\x02\x03CXX\xaa\x02\n" +
	"Crawler.V1\xca\x02\n" +
	"Crawler\\V1\xe2\x02\x16Crawler\\V1\\GPBMetadata\xea\x02\vCrawler::V1b\x06proto3"

var file_v1_service_proto_goTypes = []any{
	(*ListJobsRequest)(nil),                 // 0: crawler.v1.ListJobsRequest
	(*CreateJobRequest)(nil),                // 1: crawler.v1.CreateJobRequest
	(*GetJobRequest)(nil),                   // 2: crawler.v1.GetJobRequest
	(*GetJobExportFileURLRequest)(nil),      // 3: crawler.v1.GetJobExportFileURLRequest
	(*DeleteJobRequest)(nil),                // 4: crawler.v1.DeleteJobRequest
	(*GetTaskRequest)(nil),                  // 5: crawler.v1.GetTaskRequest
	(*ListTasksByJobRequest)(nil),           // 6: crawler.v1.ListTasksByJobRequest
	(*GetTaskAnalyticsRequest)(nil),         // 7: crawler.v1.GetTaskAnalyticsRequest
	(*GetTaskFileURLRequest)(nil),           // 8: crawler.v1.GetTaskFileURLRequest
	(*CreatePreviewRequest)(nil),            // 9: crawler.v1.CreatePreviewRequest
	(*GetPreviewRequest)(nil),               // 10: crawler.v1.GetPreviewRequest
	(*RegisterRequest)(nil),                 // 11: crawler.v1.RegisterRequest
	(*LoginRequest)(nil),                    // 12: crawler.v1.LoginRequest
	(*RefreshRequest)(nil),                  // 13: crawler.v1.RefreshRequest
	(*LogoutRequest)(nil),                   // 14: crawler.v1.LogoutRequest
	(*ListUsersRequest)(nil),                // 15: crawler.v1.ListUsersRequest
	(*UpdateUserRoleRequest)(nil),           // 16: crawler.v1.UpdateUserRoleRequest
	(*ListQueueEndpointsRequest)(nil),       // 17: crawler.v1.ListQueueEndpointsRequest
	(*CreateQueueEndpointRequest)(nil),      // 18: crawler.v1.CreateQueueEndpointRequest
	(*UpdateQueueEndpointRequest)(nil),      // 19: crawler.v1.UpdateQueueEndpointRequest
	(*DeleteQueueEndpointRequest)(nil),      // 20: crawler.v1.DeleteQueueEndpointRequest
	(*ListQueueRoutingRulesRequest)(nil),    // 21: crawler.v1.ListQueueRoutingRulesRequest
	(*UpsertQueueRoutingRulesRequest)(nil),  // 22: crawler.v1.UpsertQueueRoutingRulesRequest
	(*WorkerHeartbeat)(nil),                 // 23: crawler.v1.WorkerHeartbeat
	(*ListWorkersRequest)(nil),              // 24: crawler.v1.ListWorkersRequest
	(*DrainWorkerRequest)(nil),              // 25: crawler.v1.DrainWorkerRequest
	(*ForceKillWorkerRequest)(nil),          // 26: crawler.v1.ForceKillWorkerRequest
	(*ListJobsResponse)(nil),                // 27: crawler.v1.ListJobsResponse
	(*CreateJobResponse)(nil),               // 28: crawler.v1.CreateJobResponse
	(*GetJobResponse)(nil),                  // 29: crawler.v1.GetJobResponse
	(*GetJobExportFileURLResponse)(nil),     // 30: crawler.v1.GetJobExportFileURLResponse
	(*DeleteJobResponse)(nil),               // 31: crawler.v1.DeleteJobResponse
	(*GetTaskResponse)(nil),                 // 32: crawler.v1.GetTaskResponse
	(*ListTasksByJobResponse)(nil),          // 33: crawler.v1.ListTasksByJobResponse
	(*GetTaskAnalyticsResponse)(nil),        // 34: crawler.v1.GetTaskAnalyticsResponse
	(*GetTaskFileURLResponse)(nil),          // 35: crawler.v1.GetTaskFileURLResponse
	(*CreatePreviewResponse)(nil),           // 36: crawler.v1.CreatePreviewResponse
	(*GetPreviewResponse)(nil),              // 37: crawler.v1.GetPreviewResponse
	(*RegisterResponse)(nil),                // 38: crawler.v1.RegisterResponse
	(*LoginResponse)(nil),                   // 39: crawler.v1.LoginResponse
	(*RefreshResponse)(nil),                 // 40: crawler.v1.RefreshResponse
	(*LogoutResponse)(nil),                  // 41: crawler.v1.LogoutResponse
	(*ListUsersResponse)(nil),               // 42: crawler.v1.ListUsersResponse
	(*UpdateUserRoleResponse)(nil),          // 43: crawler.v1.UpdateUserRoleResponse
	(*ListQueueEndpointsResponse)(nil),      // 44: crawler.v1.ListQueueEndpointsResponse
	(*CreateQueueEndpointResponse)(nil),     // 45: crawler.v1.CreateQueueEndpointResponse
	(*UpdateQueueEndpointResponse)(nil),     // 46: crawler.v1.UpdateQueueEndpointResponse
	(*DeleteQueueEndpointResponse)(nil),     // 47: crawler.v1.DeleteQueueEndpointResponse
	(*ListQueueRoutingRulesResponse)(nil),   // 48: crawler.v1.ListQueueRoutingRulesResponse
	(*UpsertQueueRoutingRulesResponse)(nil), // 49: crawler.v1.UpsertQueueRoutingRulesResponse
	(*WorkerCommand)(nil),                   // 50: crawler.v1.WorkerCommand
	(*ListWorkersResponse)(nil),             // 51: crawler.v1.ListWorkersResponse
	(*DrainWorkerResponse)(nil),             // 52: crawler.v1.DrainWorkerResponse
	(*ForceKillWorkerResponse)(nil),         // 53: crawler.v1.ForceKillWorkerResponse
}
var file_v1_service_proto_depIdxs = []int32{
	0,  // 0: crawler.v1.CrawlerService.ListJobs:input_type -> crawler.v1.ListJobsRequest
	1,  // 1: crawler.v1.CrawlerService.CreateJob:input_type -> crawler.v1.CreateJobRequest
	2,  // 2: crawler.v1.CrawlerService.GetJob:input_type -> crawler.v1.GetJobRequest
	3,  // 3: crawler.v1.CrawlerService.GetJobExportFileURL:input_type -> crawler.v1.GetJobExportFileURLRequest
	4,  // 4: crawler.v1.CrawlerService.DeleteJob:input_type -> crawler.v1.DeleteJobRequest
	5,  // 5: crawler.v1.CrawlerService.GetTask:input_type -> crawler.v1.GetTaskRequest
	6,  // 6: crawler.v1.CrawlerService.ListTasksByJob:input_type -> crawler.v1.ListTasksByJobRequest
	7,  // 7: crawler.v1.CrawlerService.GetTaskAnalytics:input_type -> crawler.v1.GetTaskAnalyticsRequest
	8,  // 8: crawler.v1.CrawlerService.GetTaskFileURL:input_type -> crawler.v1.GetTaskFileURLRequest
	9,  // 9: crawler.v1.PreviewService.CreatePreview:input_type -> crawler.v1.CreatePreviewRequest
	10, // 10: crawler.v1.PreviewService.GetPreview:input_type -> crawler.v1.GetPreviewRequest
	11, // 11: crawler.v1.AuthService.Register:input_type -> crawler.v1.RegisterRequest
	12, // 12: crawler.v1.AuthService.Login:input_type -> crawler.v1.LoginRequest
	13, // 13: crawler.v1.AuthService.Refresh:input_type -> crawler.v1.RefreshRequest
	14, // 14: crawler.v1.AuthService.Logout:input_type -> crawler.v1.LogoutRequest
	15, // 15: crawler.v1.UserService.ListUsers:input_type -> crawler.v1.ListUsersRequest
	16, // 16: crawler.v1.UserService.UpdateUserRole:input_type -> crawler.v1.UpdateUserRoleRequest
	17, // 17: crawler.v1.QueueAdminService.ListQueueEndpoints:input_type -> crawler.v1.ListQueueEndpointsRequest
	18, // 18: crawler.v1.QueueAdminService.CreateQueueEndpoint:input_type -> crawler.v1.CreateQueueEndpointRequest
	19, // 19: crawler.v1.QueueAdminService.UpdateQueueEndpoint:input_type -> crawler.v1.UpdateQueueEndpointRequest
	20, // 20: crawler.v1.QueueAdminService.DeleteQueueEndpoint:input_type -> crawler.v1.DeleteQueueEndpointRequest
	21, // 21: crawler.v1.QueueAdminService.ListQueueRoutingRules:input_type -> crawler.v1.ListQueueRoutingRulesRequest
	22, // 22: crawler.v1.QueueAdminService.UpsertQueueRoutingRules:input_type -> crawler.v1.UpsertQueueRoutingRulesRequest
	23, // 23: crawler.v1.WorkerService.WorkerStream:input_type -> crawler.v1.WorkerHeartbeat
	24, // 24: crawler.v1.WorkerService.ListWorkers:input_type -> crawler.v1.ListWorkersRequest
	25, // 25: crawler.v1.WorkerService.DrainWorker:input_type -> crawler.v1.DrainWorkerRequest
	26, // 26: crawler.v1.WorkerService.ForceKillWorker:input_type -> crawler.v1.ForceKillWorkerRequest
	27, // 27: crawler.v1.CrawlerService.ListJobs:output_type -> crawler.v1.ListJobsResponse
	28, // 28: crawler.v1.CrawlerService.CreateJob:output_type -> crawler.v1.CreateJobResponse
	29, // 29: crawler.v1.CrawlerService.GetJob:output_type -> crawler.v1.GetJobResponse
	30, // 30: crawler.v1.CrawlerService.GetJobExportFileURL:output_type -> crawler.v1.GetJobExportFileURLResponse
	31, // 31: crawler.v1.CrawlerService.DeleteJob:output_type -> crawler.v1.DeleteJobResponse
	32, // 32: crawler.v1.CrawlerService.GetTask:output_type -> crawler.v1.GetTaskResponse
	33, // 33: crawler.v1.CrawlerService.ListTasksByJob:output_type -> crawler.v1.ListTasksByJobResponse
	34, // 34: crawler.v1.CrawlerService.GetTaskAnalytics:output_type -> crawler.v1.GetTaskAnalyticsResponse
	35, // 35: crawler.v1.CrawlerService.GetTaskFileURL:output_type -> crawler.v1.GetTaskFileURLResponse
	36, // 36: crawler.v1.PreviewService.CreatePreview:output_type -> crawler.v1.CreatePreviewResponse
	37, // 37: crawler.v1.PreviewService.GetPreview:output_type -> crawler.v1.GetPreviewResponse
	38, // 38: crawler.v1.AuthService.Register:output_type -> crawler.v1.RegisterResponse
	39, // 39: crawler.v1.AuthService.Login:output_type -> crawler.v1.LoginResponse
	40, // 40: crawler.v1.AuthService.Refresh:output_type -> crawler.v1.RefreshResponse
	41, // 41: crawler.v1.AuthService.Logout:output_type -> crawler.v1.LogoutResponse
	42, // 42: crawler.v1.UserService.ListUsers:output_type -> crawler.v1.ListUsersResponse
	43, // 43: crawler.v1.UserService.UpdateUserRole:output_type -> crawler.v1.UpdateUserRoleResponse
	44, // 44: crawler.v1.QueueAdminService.ListQueueEndpoints:output_type -> crawler.v1.ListQueueEndpointsResponse
	45, // 45: crawler.v1.QueueAdminService.CreateQueueEndpoint:output_type -> crawler.v1.CreateQueueEndpointResponse
	46, // 46: crawler.v1.QueueAdminService.UpdateQueueEndpoint:output_type -> crawler.v1.UpdateQueueEndpointResponse
	47, // 47: crawler.v1.QueueAdminService.DeleteQueueEndpoint:output_type -> crawler.v1.DeleteQueueEndpointResponse
	48, // 48: crawler.v1.QueueAdminService.ListQueueRoutingRules:output_type -> crawler.v1.ListQueueRoutingRulesResponse
	49, // 49: crawler.v1.QueueAdminService.UpsertQueueRoutingRules:output_type -> crawler.v1.UpsertQueueRoutingRulesResponse
	50, // 50: crawler.v1.WorkerService.WorkerStream:output_type -> crawler.v1.WorkerCommand
	51, // 51: crawler.v1.WorkerService.ListWorkers:output_type -> crawler.v1.ListWorkersResponse
	52, // 52: crawler.v1.WorkerService.DrainWorker:output_type -> crawler.v1.DrainWorkerResponse
	53, // 53: crawler.v1.WorkerService.ForceKillWorker:output_type -> crawler.v1.ForceKillWorkerResponse
	27, // [27:54] is the sub-list for method output_type
	0,  // [0:27] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_service_proto_init() }
func file_v1_service_proto_init() {
	if File_v1_service_proto != nil {
		return
	}
	file_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_proto_rawDesc), len(file_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_v1_service_proto_goTypes,
		DependencyIndexes: file_v1_service_proto_depIdxs,
	}.Build()
	File_v1_service_proto = out.File
	file_v1_service_proto_goTypes = nil
	file_v1_service_proto_depIdxs = nil
}
