// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/service.proto

package crawlergrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_service_proto protoreflect.FileDescriptor

const file_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x10v1/service.proto\x12\n" +
	"crawler.v1\x1a\x0fv1/models.proto2\xf3\b\n" +
	"\x0eCrawlerService\x12E\n" +
	"\bListJobs\x12\x1b.crawler.v1.ListJobsRequest\x1a\x1c.crawler.v1.ListJobsResponse\x12H\n" +
	"\tCreateJob\x12\x1c.crawler.v1.CreateJobRequest\x1a\x1d.crawler.v1.CreateJobResponse\x12?\n" +
	"\x06GetJob\x12\x19.crawler.v1.GetJobRequest\x1a\x1a.crawler.v1.GetJobResponse\x12H\n" +
	"\tUpdateJob\x12\x1c.crawler.v1.UpdateJobRequest\x1a\x1d.crawler.v1.UpdateJobResponse\x12K\n" +
	"\n" +
	"CreateTask\x12\x1d.crawler.v1.CreateTaskRequest\x1a\x1e.crawler.v1.CreateTaskResponse\x12B\n" +
	"\aGetTask\x12\x1a.crawler.v1.GetTaskRequest\x1a\x1b.crawler.v1.GetTaskResponse\x12W\n" +
	"\x0eListTasksByJob\x12!.crawler.v1.ListTasksByJobRequest\x1a\".crawler.v1.ListTasksByJobResponse\x12K\n" +
	"\n" +
	"UpdateTask\x12\x1d.crawler.v1.UpdateTaskRequest\x1a\x1e.crawler.v1.UpdateTaskResponse\x12W\n" +
	"\x0eCreateSnapshot\x12!.crawler.v1.CreateSnapshotRequest\x1a\".crawler.v1.CreateSnapshotResponse\x12N\n" +
	"\vGetSnapshot\x12\x1e.crawler.v1.GetSnapshotRequest\x1a\x1f.crawler.v1.GetSnapshotResponse\x12f\n" +
	"\x13ListSnapshotsByTask\x12&.crawler.v1.ListSnapshotsByTaskRequest\x1a'.crawler.v1.ListSnapshotsByTaskResponse\x12Q\n" +
	"\fCreateRecord\x12\x1f.crawler.v1.CreateRecordRequest\x1a .crawler.v1.CreateRecordResponse\x12H\n" +
	"\tGetRecord\x12\x1c.crawler.v1.GetRecordRequest\x1a\x1d.crawler.v1.GetRecordResponse\x12`\n" +
	"\x11ListRecordsByTask\x12$.crawler.v1.ListRecordsByTaskRequest\x1a%.crawler.v1.ListRecordsByTaskResponseB\x90\x01\n" +
	"\x0ecom.crawler.v1B\fServiceProtoP\x01Z'distributed-crawler/pkg/api/crawlergrpc\xa2\x02\x03CXX\xaa\x02\n" +
	"Crawler.V1\xca\x02\n" +
	"Crawler\\V1\xe2\x02\x16Crawler\\V1\\GPBMetadata\xea\x02\vCrawler::V1b\x06proto3"

var file_v1_service_proto_goTypes = []any{
	(*ListJobsRequest)(nil),             // 0: crawler.v1.ListJobsRequest
	(*CreateJobRequest)(nil),            // 1: crawler.v1.CreateJobRequest
	(*GetJobRequest)(nil),               // 2: crawler.v1.GetJobRequest
	(*UpdateJobRequest)(nil),            // 3: crawler.v1.UpdateJobRequest
	(*CreateTaskRequest)(nil),           // 4: crawler.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),              // 5: crawler.v1.GetTaskRequest
	(*ListTasksByJobRequest)(nil),       // 6: crawler.v1.ListTasksByJobRequest
	(*UpdateTaskRequest)(nil),           // 7: crawler.v1.UpdateTaskRequest
	(*CreateSnapshotRequest)(nil),       // 8: crawler.v1.CreateSnapshotRequest
	(*GetSnapshotRequest)(nil),          // 9: crawler.v1.GetSnapshotRequest
	(*ListSnapshotsByTaskRequest)(nil),  // 10: crawler.v1.ListSnapshotsByTaskRequest
	(*CreateRecordRequest)(nil),         // 11: crawler.v1.CreateRecordRequest
	(*GetRecordRequest)(nil),            // 12: crawler.v1.GetRecordRequest
	(*ListRecordsByTaskRequest)(nil),    // 13: crawler.v1.ListRecordsByTaskRequest
	(*ListJobsResponse)(nil),            // 14: crawler.v1.ListJobsResponse
	(*CreateJobResponse)(nil),           // 15: crawler.v1.CreateJobResponse
	(*GetJobResponse)(nil),              // 16: crawler.v1.GetJobResponse
	(*UpdateJobResponse)(nil),           // 17: crawler.v1.UpdateJobResponse
	(*CreateTaskResponse)(nil),          // 18: crawler.v1.CreateTaskResponse
	(*GetTaskResponse)(nil),             // 19: crawler.v1.GetTaskResponse
	(*ListTasksByJobResponse)(nil),      // 20: crawler.v1.ListTasksByJobResponse
	(*UpdateTaskResponse)(nil),          // 21: crawler.v1.UpdateTaskResponse
	(*CreateSnapshotResponse)(nil),      // 22: crawler.v1.CreateSnapshotResponse
	(*GetSnapshotResponse)(nil),         // 23: crawler.v1.GetSnapshotResponse
	(*ListSnapshotsByTaskResponse)(nil), // 24: crawler.v1.ListSnapshotsByTaskResponse
	(*CreateRecordResponse)(nil),        // 25: crawler.v1.CreateRecordResponse
	(*GetRecordResponse)(nil),           // 26: crawler.v1.GetRecordResponse
	(*ListRecordsByTaskResponse)(nil),   // 27: crawler.v1.ListRecordsByTaskResponse
}
var file_v1_service_proto_depIdxs = []int32{
	0,  // 0: crawler.v1.CrawlerService.ListJobs:input_type -> crawler.v1.ListJobsRequest
	1,  // 1: crawler.v1.CrawlerService.CreateJob:input_type -> crawler.v1.CreateJobRequest
	2,  // 2: crawler.v1.CrawlerService.GetJob:input_type -> crawler.v1.GetJobRequest
	3,  // 3: crawler.v1.CrawlerService.UpdateJob:input_type -> crawler.v1.UpdateJobRequest
	4,  // 4: crawler.v1.CrawlerService.CreateTask:input_type -> crawler.v1.CreateTaskRequest
	5,  // 5: crawler.v1.CrawlerService.GetTask:input_type -> crawler.v1.GetTaskRequest
	6,  // 6: crawler.v1.CrawlerService.ListTasksByJob:input_type -> crawler.v1.ListTasksByJobRequest
	7,  // 7: crawler.v1.CrawlerService.UpdateTask:input_type -> crawler.v1.UpdateTaskRequest
	8,  // 8: crawler.v1.CrawlerService.CreateSnapshot:input_type -> crawler.v1.CreateSnapshotRequest
	9,  // 9: crawler.v1.CrawlerService.GetSnapshot:input_type -> crawler.v1.GetSnapshotRequest
	10, // 10: crawler.v1.CrawlerService.ListSnapshotsByTask:input_type -> crawler.v1.ListSnapshotsByTaskRequest
	11, // 11: crawler.v1.CrawlerService.CreateRecord:input_type -> crawler.v1.CreateRecordRequest
	12, // 12: crawler.v1.CrawlerService.GetRecord:input_type -> crawler.v1.GetRecordRequest
	13, // 13: crawler.v1.CrawlerService.ListRecordsByTask:input_type -> crawler.v1.ListRecordsByTaskRequest
	14, // 14: crawler.v1.CrawlerService.ListJobs:output_type -> crawler.v1.ListJobsResponse
	15, // 15: crawler.v1.CrawlerService.CreateJob:output_type -> crawler.v1.CreateJobResponse
	16, // 16: crawler.v1.CrawlerService.GetJob:output_type -> crawler.v1.GetJobResponse
	17, // 17: crawler.v1.CrawlerService.UpdateJob:output_type -> crawler.v1.UpdateJobResponse
	18, // 18: crawler.v1.CrawlerService.CreateTask:output_type -> crawler.v1.CreateTaskResponse
	19, // 19: crawler.v1.CrawlerService.GetTask:output_type -> crawler.v1.GetTaskResponse
	20, // 20: crawler.v1.CrawlerService.ListTasksByJob:output_type -> crawler.v1.ListTasksByJobResponse
	21, // 21: crawler.v1.CrawlerService.UpdateTask:output_type -> crawler.v1.UpdateTaskResponse
	22, // 22: crawler.v1.CrawlerService.CreateSnapshot:output_type -> crawler.v1.CreateSnapshotResponse
	23, // 23: crawler.v1.CrawlerService.GetSnapshot:output_type -> crawler.v1.GetSnapshotResponse
	24, // 24: crawler.v1.CrawlerService.ListSnapshotsByTask:output_type -> crawler.v1.ListSnapshotsByTaskResponse
	25, // 25: crawler.v1.CrawlerService.CreateRecord:output_type -> crawler.v1.CreateRecordResponse
	26, // 26: crawler.v1.CrawlerService.GetRecord:output_type -> crawler.v1.GetRecordResponse
	27, // 27: crawler.v1.CrawlerService.ListRecordsByTask:output_type -> crawler.v1.ListRecordsByTaskResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_service_proto_init() }
func file_v1_service_proto_init() {
	if File_v1_service_proto != nil {
		return
	}
	file_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_proto_rawDesc), len(file_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_proto_goTypes,
		DependencyIndexes: file_v1_service_proto_depIdxs,
	}.Build()
	File_v1_service_proto = out.File
	file_v1_service_proto_goTypes = nil
	file_v1_service_proto_depIdxs = nil
}
