apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-infra-secrets
  namespace: {{ include "distributed-crawler-infra.namespace" . }}
  labels:
    {{- include "distributed-crawler-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  postgresql-password: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  {{- if .Values.rabbitmq.enabled }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  minio-root-password: {{ .Values.minio.auth.rootPassword | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ .Values.redis.auth.password | quote }}
  {{- end }}
  {{- if .Values.grafana.enabled }}
  grafana-admin-password: {{ .Values.grafana.auth.adminPassword | quote }}
  {{- end }}
