apiVersion: v2
name: distributed-crawler
description: A Helm chart for Distributed Crawling System
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - crawler
  - distributed
  - golang
  - grpc

maintainers:
  - name: distributed-crawler-team
